GET http://localhost:8000/api/grocery-shopping/v1/market?location[latitude]=-23.555537&location[longitude]=-46.825409&location[radius]=3000&expand=true
Content-Type: application/json
x-authorization-token: {{token}}

### get market by id
GET http://localhost:8000/api/grocery-shopping/v1/market/1
Content-Type: application/json
x-authorization-token: {{token}}
-23.656763, -47.053584
-23.528884, -46.834878
-23.551956, -46.948736
-23.555537, -46.825409
### get market list
GET http://localhost:8000/api/grocery-shopping/v1/market
Content-Type: application/json
x-authorization-token: {{token}}

### add market
POST http://localhost:8000/api/grocery-shopping/v1/market
Content-Type: application/json
x-authorization-token: {{token}}

{
  "marketName": "Assai",
  "description": "Assai Cotia",
  "location": {
    "latitude": 1.23,
    "longitude": 4.56
  }
}