/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */

export type AddProductToCartBody = {
  /** @minLength 1 */
  name: string;
  /** @exclusiveMinimum 0 */
  amount: number;
  /** @exclusiveMinimum 0 */
  price: number;
  /** @exclusiveMinimum 0 */
  wholesaleMinAmount?: number;
  /** @exclusiveMinimum 0 */
  wholesalePrice?: number;
};
