/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */
import type { AddUserBodyData } from './add-user-body-data';
import type { AddUserBodyType } from './add-user-body-type';

export type AddUserBody = {
  type: AddUserBodyType;
  data: AddUserBodyData;
  [key: string]: unknown;
};
