/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */
import type { AddProductToCart500Code } from './add-product-to-cart500-code';

export type AddProductToCart500 = {
  code: AddProductToCart500Code;
  /** Human readable error message */
  message: string;
};
