/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */

export type AddProductToCart422Code = typeof AddProductToCart422Code[keyof typeof AddProductToCart422Code];


export const AddProductToCart422Code = {
  SHOPPING_EVENT_ALREADY_ENDED_EXCEPTION: 'SHOPPING_EVENT_ALREADY_ENDED_EXCEPTION',
} as const;
