/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */

export type AddProductToCart404Code = typeof AddProductToCart404Code[keyof typeof AddProductToCart404Code];


export const AddProductToCart404Code = {
  SHOPPING_EVENT_NOT_FOUND_EXCEPTION: 'SHOPPING_EVENT_NOT_FOUND_EXCEPTION',
} as const;
