/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */
import type { CreateFamily201MembersItem } from './create-family201-members-item';
import type { CreateFamily201Owner } from './create-family201-owner';

/**
 * Family created successfully
 */
export type CreateFamily201 = {
  /**
   * @minLength 3
   * @maxLength 100
   */
  name: string;
  description?: string;
  owner: CreateFamily201Owner;
  inviteCode?: string;
  members?: CreateFamily201MembersItem[];
  createdAt: string;
  createdBy: string;
};
