/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */

export type CreateFamilyBody = {
  /**
   * @minLength 3
   * @maxLength 100
   */
  name: string;
  description?: string;
};
