/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */
import type { CreateGroup500Code } from './create-group500-code';

export type CreateGroup500 = {
  code: CreateGroup500Code;
  /** Human readable error message */
  message: string;
};
