/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */
import type { CreateGroup201MembersItemRole } from './create-group201-members-item-role';

export type CreateGroup201MembersItem = {
  userId: string;
  name?: string;
  image?: string;
  role: CreateGroup201MembersItemRole;
  joinedAt: string;
};
