/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */

export type CreateGroup500Code = typeof CreateGroup500Code[keyof typeof CreateGroup500Code];


export const CreateGroup500Code = {
  UNEXPECTED_EXCEPTION: 'UNEXPECTED_EXCEPTION',
} as const;
