/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */

export type CreateGroup201MembersItemRole =
  (typeof CreateGroup201MembersItemRole)[keyof typeof CreateGroup201MembersItemRole];

export const CreateGroup201MembersItemRole = {
  owner: 'owner',
  moderator: 'moderator',
  member: 'member',
} as const;
