/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */
import type { CreateGroup201MembersItem } from './create-group201-members-item';

/**
 * Group details
 */
export type CreateGroup201 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /**
   * @minLength 3
   * @maxLength 100
   */
  name: string;
  description?: string;
  inviteCode?: string;
  members?: CreateGroup201MembersItem[];
  createdAt: string;
  createdBy: string;
};
