/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */
import type { CreateGroup401Code } from './create-group401-code';

export type CreateGroup401 = {
  code: CreateGroup401Code;
  /** Human readable error message */
  message: string;
};
