/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */

export type DeleteGroup401Code = typeof DeleteGroup401Code[keyof typeof DeleteGroup401Code];


export const DeleteGroup401Code = {
  UNAUTHORIZED_EXCEPTION: 'UNAUTHORIZED_EXCEPTION',
} as const;
