/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteGroup500Code } from './delete-group500-code';

export type DeleteGroup500 = {
  code: DeleteGroup500Code;
  /** Human readable error message */
  message: string;
};
