/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */
import type { EndShoppingEvent401Code } from './end-shopping-event401-code';

export type EndShoppingEvent401 = {
  code: EndShoppingEvent401Code;
  /** Human readable error message */
  message: string;
};
