/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */
import type { EndShoppingEvent500Code } from './end-shopping-event500-code';

export type EndShoppingEvent500 = {
  code: EndShoppingEvent500Code;
  /** Human readable error message */
  message: string;
};
