/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */

export type EndShoppingEvent200Status =
  (typeof EndShoppingEvent200Status)[keyof typeof EndShoppingEvent200Status];

export const EndShoppingEvent200Status = {
  CANCELED: 'CANCELED',
  FINISHED: 'FINISHED',
  ONGOING: 'ONGOING',
} as const;
