/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */

export type EndShoppingEvent404Code = typeof EndShoppingEvent404Code[keyof typeof EndShoppingEvent404Code];


export const EndShoppingEvent404Code = {
  SHOPPING_EVENT_NOT_FOUND_EXCEPTION: 'SHOPPING_EVENT_NOT_FOUND_EXCEPTION',
} as const;
