/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */
import type { EndShoppingEvent200Market } from './end-shopping-event200-market';
import type { EndShoppingEvent200ProductsItem } from './end-shopping-event200-products-item';
import type { EndShoppingEvent200Status } from './end-shopping-event200-status';
import type { EndShoppingEvent200Totals } from './end-shopping-event200-totals';

export type EndShoppingEvent200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  status: EndShoppingEvent200Status;
  market: EndShoppingEvent200Market;
  totals: EndShoppingEvent200Totals;
  products: EndShoppingEvent200ProductsItem[];
  elapsedTime?: number;
  createdAt: string;
  finishedAt?: string;
  createdBy: string;
};
