/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */

export type EndShoppingEvent200Totals = {
  retailTotal: number;
  wholesaleTotal: number;
  paidValue?: number;
  savingsValue?: number;
  savingsPercentage?: number;
  retailPaidDifferenceValue?: number;
  wholesalePaidDifferenceValue?: number;
  totalItemsDistinct: number;
  totalItemsQuantity: number;
  averagePricePerUnit: number;
  highestPrice: number;
  lowestPrice: number;
};
