/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */

export type GetInviteInfo403Code = typeof GetInviteInfo403Code[keyof typeof GetInviteInfo403Code];


export const GetInviteInfo403Code = {
  USER_NOT_IN_GROUP_EXCEPTION: 'USER_NOT_IN_GROUP_EXCEPTION',
} as const;
