/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */

export type GetMarketById200 = {
  id: string;
  name: string;
  formattedAddress: string;
  city: string;
  neighborhood: string;
  latitude: number;
  longitude: number;
  distance?: number;
  createdAt: string;
  lastUpdatedAt: string;
};
