/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */

export type GetShoppingEventList422 = {
  code: 'SHOPPING_EVENT_ALREADY_ENDED_EXCEPTION';
  /** Human readable error message */
  message: string;
} | {
  code: 'SHOPPING_EVENT_EMPTY_CART_EXCEPTION';
  /** Human readable error message */
  message: string;
};
