/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */

export type GetShoppingEventById200Status =
  (typeof GetShoppingEventById200Status)[keyof typeof GetShoppingEventById200Status];

export const GetShoppingEventById200Status = {
  canceled: 'canceled',
  finished: 'finished',
  ongoing: 'ongoing',
} as const;
