/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */
import type { GetShoppingEventById200Market } from './get-shopping-event-by-id200-market';
import type { GetShoppingEventById200ProductsItem } from './get-shopping-event-by-id200-products-item';
import type { GetShoppingEventById200Status } from './get-shopping-event-by-id200-status';
import type { GetShoppingEventById200Totals } from './get-shopping-event-by-id200-totals';

export type GetShoppingEventById200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  status: GetShoppingEventById200Status;
  market?: GetShoppingEventById200Market;
  totals: GetShoppingEventById200Totals;
  products: GetShoppingEventById200ProductsItem[];
  elapsedTime?: number;
  createdAt: string;
  finishedAt?: string;
  createdBy: string;
};
