/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */

export type GetShoppingEventList404Code = typeof GetShoppingEventList404Code[keyof typeof GetShoppingEventList404Code];


export const GetShoppingEventList404Code = {
  SHOPPING_EVENT_NOT_FOUND_EXCEPTION: 'SHOPPING_EVENT_NOT_FOUND_EXCEPTION',
} as const;
