/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */
import type { GetInviteInfo401Code } from './get-invite-info401-code';

export type GetInviteInfo401 = {
  code: GetInviteInfo401Code;
  /** Human readable error message */
  message: string;
};
