/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */
import type { GetInviteInfo403Code } from './get-invite-info403-code';

export type GetInviteInfo403 = {
  code: GetInviteInfo403Code;
  /** Human readable error message */
  message: string;
};
