/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */

export type GetFamily200MembersItem = {
  id: string;
  externalId: string;
  name?: string;
  picture?: string;
  email: string;
};
