/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */
import type { GetShoppingEventList500Code } from './get-shopping-event-list500-code';

export type GetShoppingEventList500 = {
  code: GetShoppingEventList500Code;
  /** Human readable error message */
  message: string;
};
