/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */

export type GetGroups200ItemMembersItemRole =
  (typeof GetGroups200ItemMembersItemRole)[keyof typeof GetGroups200ItemMembersItemRole];

export const GetGroups200ItemMembersItemRole = {
  owner: 'owner',
  moderator: 'moderator',
  member: 'member',
} as const;
