/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */
import type { GetInviteInfo500Code } from './get-invite-info500-code';

export type GetInviteInfo500 = {
  code: GetInviteInfo500Code;
  /** Human readable error message */
  message: string;
};
