/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */
import type { GetGroups200ItemMembersItemRole } from './get-groups200-item-members-item-role';

export type GetGroups200ItemMembersItem = {
  userId: string;
  name?: string;
  image?: string;
  role: GetGroups200ItemMembersItemRole;
  joinedAt: string;
};
