/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */

export type GetShoppingEventListStatus =
  (typeof GetShoppingEventListStatus)[keyof typeof GetShoppingEventListStatus];

export const GetShoppingEventListStatus = {
  canceled: 'canceled',
  finished: 'finished',
  ongoing: 'ongoing',
} as const;
