/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */
import type { GetFamily200MembersItem } from './get-family200-members-item';
import type { GetFamily200Owner } from './get-family200-owner';

/**
 * Family created successfully
 */
export type GetFamily200 = {
  /**
   * @minLength 3
   * @maxLength 100
   */
  name: string;
  description?: string;
  owner: GetFamily200Owner;
  inviteCode?: string;
  members?: GetFamily200MembersItem[];
  createdAt: string;
  createdBy: string;
};
