/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */

export type GetShoppingEventListOrderDirection = typeof GetShoppingEventListOrderDirection[keyof typeof GetShoppingEventListOrderDirection];


export const GetShoppingEventListOrderDirection = {
  desc: 'desc',
  asc: 'asc',
} as const;
