/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */
import type { GetShoppingEventList200ItemsItem } from './get-shopping-event-list200-items-item';

export type GetShoppingEventList200 = {
  total: number;
  items: GetShoppingEventList200ItemsItem[];
};
