/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */

export type GetShoppingEventList200ItemsItemTotals = {
  retailTotal?: number;
  wholesaleTotal?: number;
  totalItemsDistinct?: number;
  totalItemsQuantity?: number;
  savingsPercentage?: number;
};
