/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */

export type JoinGroup404Code = typeof JoinGroup404Code[keyof typeof JoinGroup404Code];


export const JoinGroup404Code = {
  USER_NOT_FOUND_EXCEPTION: 'USER_NOT_FOUND_EXCEPTION',
} as const;
