/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */
import type { JoinGroup400Code } from './join-group400-code';

export type JoinGroup400 = {
  code: JoinGroup400Code;
  /** Human readable error message */
  message: string;
};
