/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */

export type JoinGroup400Code = typeof JoinGroup400Code[keyof typeof JoinGroup400Code];


export const JoinGroup400Code = {
  INVALID_GROUP_INVITATION_CODE_EXCEPTION: 'INVALID_GROUP_INVITATION_CODE_EXCEPTION',
} as const;
