/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */
import type { JoinGroup500Code } from './join-group500-code';

export type JoinGroup500 = {
  code: JoinGroup500Code;
  /** Human readable error message */
  message: string;
};
