/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */
import type { JoinGroup401Code } from './join-group401-code';

export type JoinGroup401 = {
  code: JoinGroup401Code;
  /** Human readable error message */
  message: string;
};
