/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */
import type { LeaveGroup401Code } from './leave-group401-code';

export type LeaveGroup401 = {
  code: LeaveGroup401Code;
  /** Human readable error message */
  message: string;
};
