/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */

export type LeaveGroup400Code = typeof LeaveGroup400Code[keyof typeof LeaveGroup400Code];


export const LeaveGroup400Code = {
  LAST_OWNER_CANNOT_LEAVE_EXCEPTION: 'LAST_OWNER_CANNOT_LEAVE_EXCEPTION',
} as const;
