/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */

export type ListMarkets401Code = typeof ListMarkets401Code[keyof typeof ListMarkets401Code];


export const ListMarkets401Code = {
  UNAUTHORIZED_EXCEPTION: 'UNAUTHORIZED_EXCEPTION',
} as const;
