/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */
import type { ListMarkets500Code } from './list-markets500-code';

export type ListMarkets500 = {
  code: ListMarkets500Code;
  /** Human readable error message */
  message: string;
};
