/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */
import type { ListMarkets401Code } from './list-markets401-code';

export type ListMarkets401 = {
  code: ListMarkets401Code;
  /** Human readable error message */
  message: string;
};
