/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */

export type ListMarketsOrderBy = typeof ListMarketsOrderBy[keyof typeof ListMarketsOrderBy];


export const ListMarketsOrderBy = {
  createdAt: 'createdAt',
  distance: 'distance',
} as const;
