/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */

export type RegenerateInviteCode403 = {
  code: string;
  message: string;
  stack?: string;
};
