/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */

export type RegenerateInviteCode401Code = typeof RegenerateInviteCode401Code[keyof typeof RegenerateInviteCode401Code];


export const RegenerateInviteCode401Code = {
  UNAUTHORIZED_EXCEPTION: 'UNAUTHORIZED_EXCEPTION',
} as const;
