/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */

export type RegenerateInviteCode403 = {
  code: 'UNAUTHORIZED_GROUP_OPERATION_EXCEPTION';
  /** Human readable error message */
  message: string;
} | {
  code: 'USER_NOT_IN_GROUP_EXCEPTION';
  /** Human readable error message */
  message: string;
};
