/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */
import type { RegenerateInviteCode500Code } from './regenerate-invite-code500-code';

export type RegenerateInviteCode500 = {
  code: RegenerateInviteCode500Code;
  /** Human readable error message */
  message: string;
};
