/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */
import type { RegenerateInviteCode401Code } from './regenerate-invite-code401-code';

export type RegenerateInviteCode401 = {
  code: RegenerateInviteCode401Code;
  /** Human readable error message */
  message: string;
};
