/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */

export type RegenerateInviteCode500Code = typeof RegenerateInviteCode500Code[keyof typeof RegenerateInviteCode500Code];


export const RegenerateInviteCode500Code = {
  UNEXPECTED_EXCEPTION: 'UNEXPECTED_EXCEPTION',
} as const;
