/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */

export type RemoveProductFromCart500Code = typeof RemoveProductFromCart500Code[keyof typeof RemoveProductFromCart500Code];


export const RemoveProductFromCart500Code = {
  UNEXPECTED_EXCEPTION: 'UNEXPECTED_EXCEPTION',
} as const;
