/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */
import type { RemoveProductFromCart422Code } from './remove-product-from-cart422-code';

export type RemoveProductFromCart422 = {
  code: RemoveProductFromCart422Code;
  /** Human readable error message */
  message: string;
};
