/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */
import type { RemoveMember401Code } from './remove-member401-code';

export type RemoveMember401 = {
  code: RemoveMember401Code;
  /** Human readable error message */
  message: string;
};
