/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */
import type { RemoveMember500Code } from './remove-member500-code';

export type RemoveMember500 = {
  code: RemoveMember500Code;
  /** Human readable error message */
  message: string;
};
