/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */
import type { RemoveProductFromCart401Code } from './remove-product-from-cart401-code';

export type RemoveProductFromCart401 = {
  code: RemoveProductFromCart401Code;
  /** Human readable error message */
  message: string;
};
