/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */

export type RemoveProductFromCart401Code = typeof RemoveProductFromCart401Code[keyof typeof RemoveProductFromCart401Code];


export const RemoveProductFromCart401Code = {
  UNAUTHORIZED_EXCEPTION: 'UNAUTHORIZED_EXCEPTION',
} as const;
