/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */
import type { RemoveProductFromCart500Code } from './remove-product-from-cart500-code';

export type RemoveProductFromCart500 = {
  code: RemoveProductFromCart500Code;
  /** Human readable error message */
  message: string;
};
