/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */
import type { ScanProduct200MatchType } from './scan-product200-match-type';
import type { ScanProduct200Product } from './scan-product200-product';
import type { ScanProduct200VariableWeight } from './scan-product200-variable-weight';

export type ScanProduct200 = {
  barcode: string;
  matchType: ScanProduct200MatchType;
  product?: ScanProduct200Product;
  variableWeight?: ScanProduct200VariableWeight;
};
