/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */
import type { ScanProduct401Code } from './scan-product401-code';

export type ScanProduct401 = {
  code: ScanProduct401Code;
  /** Human readable error message */
  message: string;
};
