/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */

export type ScanProduct200MatchType =
  (typeof ScanProduct200MatchType)[keyof typeof ScanProduct200MatchType];

export const ScanProduct200MatchType = {
  LOCAL: 'LOCAL',
  EXTERNAL: 'EXTERNAL',
  VARIABLE_WEIGHT: 'VARIABLE_WEIGHT',
  NOT_FOUND: 'NOT_FOUND',
} as const;
