/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */

export type ScanProduct404Code = typeof ScanProduct404Code[keyof typeof ScanProduct404Code];


export const ScanProduct404Code = {
  PRODUCT_NOT_FOUND_EXCEPTION: 'PRODUCT_NOT_FOUND_EXCEPTION',
} as const;
