/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */
import type { ScanProduct500Code } from './scan-product500-code';

export type ScanProduct500 = {
  code: ScanProduct500Code;
  /** Human readable error message */
  message: string;
};
