/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */

export type SearchProduct500Code = typeof SearchProduct500Code[keyof typeof SearchProduct500Code];


export const SearchProduct500Code = {
  UNEXPECTED_EXCEPTION: 'UNEXPECTED_EXCEPTION',
} as const;
