/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */

export type SearchProductParams = {
/**
 * Search query (name or brand)
 * @minLength 2
 */
searchQuery: string;
/**
 * @minimum 0
 * @maximum 9007199254740991
 */
pageIndex?: number;
/**
 * @minimum 1
 * @maximum 100
 */
pageSize?: number;
};
