/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */
import type { SearchProducts200ProductsItem } from './search-products200-products-item';

export type SearchProducts200 = {
  products: SearchProducts200ProductsItem[];
};
