/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */

export type SearchProductsParams = {
  /**
   * Search query (name or brand)
   * @minLength 2
   */
  q: string;
};
