/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */
import type { SearchProduct200ItemsItem } from './search-product200-items-item';

export type SearchProduct200 = {
  items: SearchProduct200ItemsItem[];
  total: number;
  nextPageIndex?: number;
};
