/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */
import type { SearchProduct500Code } from './search-product500-code';

export type SearchProduct500 = {
  code: SearchProduct500Code;
  /** Human readable error message */
  message: string;
};
