/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */
import type { SearchProduct401Code } from './search-product401-code';

export type SearchProduct401 = {
  code: SearchProduct401Code;
  /** Human readable error message */
  message: string;
};
