/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */

export type SearchProduct404Code = typeof SearchProduct404Code[keyof typeof SearchProduct404Code];


export const SearchProduct404Code = {
  PRODUCT_NOT_FOUND_EXCEPTION: 'PRODUCT_NOT_FOUND_EXCEPTION',
} as const;
