/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */

export type SignInEmail200 = {
  user: {
  id: string;
  name: string;
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string;
  emailVerified: boolean;
  /** @nullable */
  image?: string | null;
  createdAt: string;
  updatedAt: string;
};
  session: {
  id?: string;
  expiresAt: string;
  token: string;
  createdAt: string;
  updatedAt: string;
  /** @nullable */
  ipAddress?: string | null;
  /** @nullable */
  userAgent?: string | null;
  userId: string;
};
} | {
  /** @nullable */
  token: string | null;
  user: {
  id: string;
  name: string;
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string;
  emailVerified: boolean;
  /** @nullable */
  image?: string | null;
  createdAt: string;
  updatedAt: string;
};
} | {
  redirect: boolean;
  token: string;
  url?: string;
  user: {
  id: string;
  name: string;
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string;
  emailVerified: boolean;
  /** @nullable */
  image?: string | null;
  createdAt: string;
  updatedAt: string;
};
} | {
  success: boolean;
} | {
  url: string;
  redirect: boolean;
} | null;
