/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */
import type { SignInSocialBodyProvider } from './sign-in-social-body-provider';

export type SignInSocialBody = {
  provider: SignInSocialBodyProvider;
  callbackURL?: string;
  errorCallbackURL?: string;
  newUserCallbackURL?: string;
};
