/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */

export type SignInSocialBodyProvider = typeof SignInSocialBodyProvider[keyof typeof SignInSocialBodyProvider];


export const SignInSocialBodyProvider = {
  google: 'google',
} as const;
