/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */
import type { StartShoppingEvent401Code } from './start-shopping-event401-code';

export type StartShoppingEvent401 = {
  code: StartShoppingEvent401Code;
  /** Human readable error message */
  message: string;
};
