/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */

export type StartShoppingEvent401Code = typeof StartShoppingEvent401Code[keyof typeof StartShoppingEvent401Code];


export const StartShoppingEvent401Code = {
  UNAUTHORIZED_EXCEPTION: 'UNAUTHORIZED_EXCEPTION',
} as const;
