/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */

export type StartShoppingEvent500Code = typeof StartShoppingEvent500Code[keyof typeof StartShoppingEvent500Code];


export const StartShoppingEvent500Code = {
  UNEXPECTED_EXCEPTION: 'UNEXPECTED_EXCEPTION',
} as const;
