/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */
import type { StartShoppingEvent404Code } from './start-shopping-event404-code';

export type StartShoppingEvent404 = {
  code: StartShoppingEvent404Code;
  /** Human readable error message */
  message: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  marketId?: string;
};
