/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */
import type { StartShoppingEvent500Code } from './start-shopping-event500-code';

export type StartShoppingEvent500 = {
  code: StartShoppingEvent500Code;
  /** Human readable error message */
  message: string;
};
