/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */

export type StartShoppingEvent404Code = typeof StartShoppingEvent404Code[keyof typeof StartShoppingEvent404Code];


export const StartShoppingEvent404Code = {
  MARKET_NOT_FOUND_EXCEPTION: 'MARKET_NOT_FOUND_EXCEPTION',
} as const;
