/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */

export type UpdateProductInCart422Code = typeof UpdateProductInCart422Code[keyof typeof UpdateProductInCart422Code];


export const UpdateProductInCart422Code = {
  SHOPPING_EVENT_ALREADY_ENDED_EXCEPTION: 'SHOPPING_EVENT_ALREADY_ENDED_EXCEPTION',
} as const;
