/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateMemberRole500Code } from './update-member-role500-code';

export type UpdateMemberRole500 = {
  code: UpdateMemberRole500Code;
  /** Human readable error message */
  message: string;
};
