/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateMemberRole401Code } from './update-member-role401-code';

export type UpdateMemberRole401 = {
  code: UpdateMemberRole401Code;
  /** Human readable error message */
  message: string;
};
