/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */

export type UpdateMemberRoleBodyRole = typeof UpdateMemberRoleBodyRole[keyof typeof UpdateMemberRoleBodyRole];


export const UpdateMemberRoleBodyRole = {
  owner: 'owner',
  moderator: 'moderator',
  member: 'member',
} as const;
