/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateProductInCart500Code } from './update-product-in-cart500-code';

export type UpdateProductInCart500 = {
  code: UpdateProductInCart500Code;
  /** Human readable error message */
  message: string;
};
