/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */

export type UpdateGroup200MembersItemRole = typeof UpdateGroup200MembersItemRole[keyof typeof UpdateGroup200MembersItemRole];


export const UpdateGroup200MembersItemRole = {
  owner: 'owner',
  moderator: 'moderator',
  member: 'member',
} as const;
