/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */

export type UpdateProductInCart500Code = typeof UpdateProductInCart500Code[keyof typeof UpdateProductInCart500Code];


export const UpdateProductInCart500Code = {
  UNEXPECTED_EXCEPTION: 'UNEXPECTED_EXCEPTION',
} as const;
