/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateGroup401Code } from './update-group401-code';

export type UpdateGroup401 = {
  code: UpdateGroup401Code;
  /** Human readable error message */
  message: string;
};
