/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateGroup200MembersItemRole } from './update-group200-members-item-role';

export type UpdateGroup200MembersItem = {
  userId: string;
  name?: string;
  image?: string;
  role: UpdateGroup200MembersItemRole;
  joinedAt: string;
};
