/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateMemberRoleBodyRole } from './update-member-role-body-role';

export type UpdateMemberRoleBody = {
  role: UpdateMemberRoleBodyRole;
};
