/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */

export type UpdateGroup401Code = typeof UpdateGroup401Code[keyof typeof UpdateGroup401Code];


export const UpdateGroup401Code = {
  UNAUTHORIZED_EXCEPTION: 'UNAUTHORIZED_EXCEPTION',
} as const;
