/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateGroup500Code } from './update-group500-code';

export type UpdateGroup500 = {
  code: UpdateGroup500Code;
  /** Human readable error message */
  message: string;
};
