/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateProductInCart401Code } from './update-product-in-cart401-code';

export type UpdateProductInCart401 = {
  code: UpdateProductInCart401Code;
  /** Human readable error message */
  message: string;
};
