/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */

export type UpdateGroup500Code = typeof UpdateGroup500Code[keyof typeof UpdateGroup500Code];


export const UpdateGroup500Code = {
  UNEXPECTED_EXCEPTION: 'UNEXPECTED_EXCEPTION',
} as const;
