export const injection = {
  application: {
    fastify: 'fastify-app',
  },
  infra: {
    marketRepositories: 'market-repositories',
    userRepositories: 'user-repositories',
    familyRepositories: 'family-repositories',
    shoppingEventRepositories: 'shopping-event-repositories',
    productRepositories: 'product-repositories',
    userInfo: 'user-info-service',
    placesHttpClient: 'places-http-client',
    places: 'places-service',
  },
  usecases: {
    getMarketList: 'get-market-list-usecase',
    getMarketById: 'get-market-by-id-usecase',
    startShoppingEvent: 'start-shopping-event-usecase',
    endShoppingEvent: 'end-shopping-event-usecase',
    getShoppingEventList: 'get-shopping-event-list-usecase',
    getShoppingEventById: 'get-shopping-event-by-id-usecase',
    addProductToCart: 'add-product-to-cart-usecase',
    updateProductInCart: 'update-product-in-cart-usecase',
    removeProductFromCart: 'remove-product-from-cart-usecase',
    getUser: 'get-user-usecase',
    addUser: 'add-user-usecase',
    addFamily: 'add-family-usecase',
    joinFamily: 'join-family-usecase',
    leaveFamily: 'leave-family-usecase',
    getFamily: 'get-family-usecase',
    removeFamilyMember: 'remove-family-member-usecase',
  },
  controllers: {
    fastify: 'fastify-controllers',
  },
};
