export const injection = {
  application: {
    fastify: 'fastify-app',
  },
  infra: {
    marketRepositories: 'market-repositories',
    userRepositories: 'user-repositories',
    groupRepositories: 'group-repositories',
    shoppingEventRepositories: 'shopping-event-repositories',
    productRepositories: 'product-repositories',
    canonicalProductRepositories: 'canonical-product-repositories',
    productIdentityRepositories: 'product-identity-repositories',
    outboxEventRepositories: 'outbox-event-repositories',
    physicalEanRepository: 'physical-ean-repository',
    externalFetchLogRepository: 'external-fetch-log-repository',
    openFoodFactsClient: 'open-food-facts-client',
    upcItemDbClient: 'upc-item-db-client',
    compositeProductClient: 'composite-product-client',
    userInfo: 'user-info-service',

    placesHttpClient: 'places-http-client',
    places: 'places-service',
    configService: 'config-service',
    settingsRepository: 'settings-repository',
    permissionService: 'permission-service',
  },
  usecases: {
    cartService: 'cart-service',
    groupService: 'group-service',
    shoppingEventService: 'shopping-event-service',
    marketService: 'market-service',
    userService: 'user-service',
    pricingConsensusService: 'pricing-consensus-service',
    searchProductsService: 'search-products-service',
    scanProductUseCase: 'scan-product-use-case',
    manualSearchUseCase: 'manual-search-use-case',
    hydrateProductUseCase: 'hydrate-product-use-case',
    hydrateProductJob: 'hydrate-product-job',

    nfcEDecoder: 'nfc-e-decoder',
    reconciliationEngine: 'reconciliation-engine',
  },
  controllers: {
    fastify: 'fastify-controllers',
    product: 'product-controller',
    shoppingEvent: 'shopping-event-controller',
    cart: 'cart-controller',
  },
};
