export const injection = {
  application: {
    fastify: 'fastify-app',
  },
  infra: {
    marketRepositories: 'market-repositories',
    userRepositories: 'user-repositories',
    groupRepositories: 'group-repositories',
    shoppingEventRepositories: 'shopping-event-repositories',
    productRepositories: 'product-repositories',
    canonicalProductRepositories: 'canonical-product-repositories',
    productIdentityRepositories: 'product-identity-repositories',
    outboxEventRepositories: 'outbox-event-repositories',
    physicalEanRepository: 'physical-ean-repository',
    externalFetchLogRepository: 'external-fetch-log-repository',
    openFoodFactsService: 'open-food-facts-service',
    upcItemDbService: 'upc-item-db-service',
    compositeProductService: 'composite-product-service',
    userInfo: 'user-info-service',

    placesHttpClient: 'places-http-client',
    places: 'places-service',
    configService: 'config-service',
    settingsRepository: 'settings-repository',
    permissionService: 'permission-service',
  },
  usecases: {
    cartManager: 'cart-manager',
    groupManager: 'group-manager',
    shoppingEventManager: 'shopping-event-manager',
    marketManager: 'market-manager',
    userManager: 'user-manager',
    priceConsensusEngine: 'price-consensus-engine',
    searchProductsService: 'search-products-service',
    productHydrator: 'product-hydrator',
    productHydratorJob: 'product-hydrator-job',

    nfcEDecoder: 'nfc-e-decoder',
    reconciliationEngine: 'reconciliation-engine',
  },
  controllers: {
    fastify: 'fastify-controllers',
    product: 'product-controller',
    shoppingEvent: 'shopping-event-controller',
    cart: 'cart-controller',
  },
};
