/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetGroupSettings200,
  UpdateGroupSettingsBody
} from './types';

import { customInstance } from '../../config/clients/custom-http-client';
import type { ErrorType , BodyType } from '../../config/clients/custom-http-client';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Retrieve all settings for a specific group
 * @summary Get group settings
 */
export const getGroupSettings = (
    groupId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetGroupSettings200>(
      {url: `/api/admin/groups/${groupId}/settings`, method: 'GET', signal
    },
      options);
    }
  



export const getGetGroupSettingsQueryKey = (groupId: string,) => {
    return [
    `/api/admin/groups/${groupId}/settings`
    ] as const;
    }

    
export const getGetGroupSettingsQueryOptions = <TData = Awaited<ReturnType<typeof getGroupSettings>>, TError = ErrorType<unknown>>(groupId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGroupSettings>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetGroupSettingsQueryKey(groupId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getGroupSettings>>> = ({ signal }) => getGroupSettings(groupId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(groupId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getGroupSettings>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetGroupSettingsQueryResult = NonNullable<Awaited<ReturnType<typeof getGroupSettings>>>
export type GetGroupSettingsQueryError = ErrorType<unknown>


export function useGetGroupSettings<TData = Awaited<ReturnType<typeof getGroupSettings>>, TError = ErrorType<unknown>>(
 groupId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGroupSettings>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGroupSettings>>,
          TError,
          Awaited<ReturnType<typeof getGroupSettings>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGroupSettings<TData = Awaited<ReturnType<typeof getGroupSettings>>, TError = ErrorType<unknown>>(
 groupId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGroupSettings>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGroupSettings>>,
          TError,
          Awaited<ReturnType<typeof getGroupSettings>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGroupSettings<TData = Awaited<ReturnType<typeof getGroupSettings>>, TError = ErrorType<unknown>>(
 groupId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGroupSettings>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get group settings
 */

export function useGetGroupSettings<TData = Awaited<ReturnType<typeof getGroupSettings>>, TError = ErrorType<unknown>>(
 groupId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGroupSettings>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetGroupSettingsQueryOptions(groupId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Update multiple settings for a specific group
 * @summary Update group settings
 */
export const updateGroupSettings = (
    groupId: string,
    updateGroupSettingsBody: BodyType<UpdateGroupSettingsBody>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/admin/groups/${groupId}/settings`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateGroupSettingsBody, signal
    },
      options);
    }
  


export const getUpdateGroupSettingsMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateGroupSettings>>, TError,{groupId: string;data: BodyType<UpdateGroupSettingsBody>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateGroupSettings>>, TError,{groupId: string;data: BodyType<UpdateGroupSettingsBody>}, TContext> => {

const mutationKey = ['updateGroupSettings'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateGroupSettings>>, {groupId: string;data: BodyType<UpdateGroupSettingsBody>}> = (props) => {
          const {groupId,data} = props ?? {};

          return  updateGroupSettings(groupId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateGroupSettingsMutationResult = NonNullable<Awaited<ReturnType<typeof updateGroupSettings>>>
    export type UpdateGroupSettingsMutationBody = BodyType<UpdateGroupSettingsBody>
    export type UpdateGroupSettingsMutationError = ErrorType<unknown>

    /**
 * @summary Update group settings
 */
export const useUpdateGroupSettings = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateGroupSettings>>, TError,{groupId: string;data: BodyType<UpdateGroupSettingsBody>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateGroupSettings>>,
        TError,
        {groupId: string;data: BodyType<UpdateGroupSettingsBody>},
        TContext
      > => {
      return useMutation(getUpdateGroupSettingsMutationOptions(options), queryClient);
    }
    