/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */

import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  BodyType,
  ErrorType,
} from '../../config/clients/custom-http-client';
import { customInstance } from '../../config/clients/custom-http-client';
import type { PatchApiAdminGroupsGroupIdSettingsBody } from './types';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getApiAdminGroupsGroupIdSettings = (
  groupId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<void>(
    { url: `/api/admin/groups/${groupId}/settings`, method: 'GET', signal },
    options,
  );
};

export const getGetApiAdminGroupsGroupIdSettingsQueryKey = (
  groupId: string,
) => {
  return [`/api/admin/groups/${groupId}/settings`] as const;
};

export const getGetApiAdminGroupsGroupIdSettingsQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiAdminGroupsGroupIdSettings>>,
  TError = ErrorType<unknown>,
>(
  groupId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getApiAdminGroupsGroupIdSettings>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetApiAdminGroupsGroupIdSettingsQueryKey(groupId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiAdminGroupsGroupIdSettings>>
  > = ({ signal }) =>
    getApiAdminGroupsGroupIdSettings(groupId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!groupId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiAdminGroupsGroupIdSettings>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetApiAdminGroupsGroupIdSettingsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiAdminGroupsGroupIdSettings>>
>;
export type GetApiAdminGroupsGroupIdSettingsQueryError = ErrorType<unknown>;

export function useGetApiAdminGroupsGroupIdSettings<
  TData = Awaited<ReturnType<typeof getApiAdminGroupsGroupIdSettings>>,
  TError = ErrorType<unknown>,
>(
  groupId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getApiAdminGroupsGroupIdSettings>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetApiAdminGroupsGroupIdSettingsQueryOptions(
    groupId,
    options,
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const patchApiAdminGroupsGroupIdSettings = (
  groupId: string,
  patchApiAdminGroupsGroupIdSettingsBody: BodyType<PatchApiAdminGroupsGroupIdSettingsBody>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<void>(
    {
      url: `/api/admin/groups/${groupId}/settings`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: patchApiAdminGroupsGroupIdSettingsBody,
      signal,
    },
    options,
  );
};

export const getPatchApiAdminGroupsGroupIdSettingsMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof patchApiAdminGroupsGroupIdSettings>>,
    TError,
    { groupId: string; data: BodyType<PatchApiAdminGroupsGroupIdSettingsBody> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof patchApiAdminGroupsGroupIdSettings>>,
  TError,
  { groupId: string; data: BodyType<PatchApiAdminGroupsGroupIdSettingsBody> },
  TContext
> => {
  const mutationKey = ['patchApiAdminGroupsGroupIdSettings'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof patchApiAdminGroupsGroupIdSettings>>,
    { groupId: string; data: BodyType<PatchApiAdminGroupsGroupIdSettingsBody> }
  > = (props) => {
    const { groupId, data } = props ?? {};

    return patchApiAdminGroupsGroupIdSettings(groupId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PatchApiAdminGroupsGroupIdSettingsMutationResult = NonNullable<
  Awaited<ReturnType<typeof patchApiAdminGroupsGroupIdSettings>>
>;
export type PatchApiAdminGroupsGroupIdSettingsMutationBody =
  BodyType<PatchApiAdminGroupsGroupIdSettingsBody>;
export type PatchApiAdminGroupsGroupIdSettingsMutationError =
  ErrorType<unknown>;

export const usePatchApiAdminGroupsGroupIdSettings = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof patchApiAdminGroupsGroupIdSettings>>,
    TError,
    { groupId: string; data: BodyType<PatchApiAdminGroupsGroupIdSettingsBody> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof patchApiAdminGroupsGroupIdSettings>>,
  TError,
  { groupId: string; data: BodyType<PatchApiAdminGroupsGroupIdSettingsBody> },
  TContext
> => {
  return useMutation(
    getPatchApiAdminGroupsGroupIdSettingsMutationOptions(options),
  );
};
