/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */

import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  BodyType,
  ErrorType,
} from '../../config/clients/custom-http-client';
import { customInstance } from '../../config/clients/custom-http-client';
import type { GetGroupSettings200, UpdateGroupSettingsBody } from './types';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Retrieve all settings for a specific group
 * @summary Get group settings
 */
export const getGroupSettings = (
  groupId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<GetGroupSettings200>(
    { url: `/api/admin/groups/${groupId}/settings`, method: 'GET', signal },
    options,
  );
};

export const getGetGroupSettingsQueryKey = (groupId: string) => {
  return [`/api/admin/groups/${groupId}/settings`] as const;
};

export const getGetGroupSettingsQueryOptions = <
  TData = Awaited<ReturnType<typeof getGroupSettings>>,
  TError = ErrorType<unknown>,
>(
  groupId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getGroupSettings>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetGroupSettingsQueryKey(groupId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getGroupSettings>>
  > = ({ signal }) => getGroupSettings(groupId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!groupId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getGroupSettings>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetGroupSettingsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getGroupSettings>>
>;
export type GetGroupSettingsQueryError = ErrorType<unknown>;

/**
 * @summary Get group settings
 */

export function useGetGroupSettings<
  TData = Awaited<ReturnType<typeof getGroupSettings>>,
  TError = ErrorType<unknown>,
>(
  groupId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getGroupSettings>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetGroupSettingsQueryOptions(groupId, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Update multiple settings for a specific group
 * @summary Update group settings
 */
export const updateGroupSettings = (
  groupId: string,
  updateGroupSettingsBody: BodyType<UpdateGroupSettingsBody>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<unknown>(
    {
      url: `/api/admin/groups/${groupId}/settings`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: updateGroupSettingsBody,
      signal,
    },
    options,
  );
};

export const getUpdateGroupSettingsMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateGroupSettings>>,
    TError,
    { groupId: string; data: BodyType<UpdateGroupSettingsBody> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateGroupSettings>>,
  TError,
  { groupId: string; data: BodyType<UpdateGroupSettingsBody> },
  TContext
> => {
  const mutationKey = ['updateGroupSettings'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateGroupSettings>>,
    { groupId: string; data: BodyType<UpdateGroupSettingsBody> }
  > = (props) => {
    const { groupId, data } = props ?? {};

    return updateGroupSettings(groupId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateGroupSettingsMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateGroupSettings>>
>;
export type UpdateGroupSettingsMutationBody = BodyType<UpdateGroupSettingsBody>;
export type UpdateGroupSettingsMutationError = ErrorType<unknown>;

/**
 * @summary Update group settings
 */
export const useUpdateGroupSettings = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateGroupSettings>>,
    TError,
    { groupId: string; data: BodyType<UpdateGroupSettingsBody> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof updateGroupSettings>>,
  TError,
  { groupId: string; data: BodyType<UpdateGroupSettingsBody> },
  TContext
> => {
  return useMutation(getUpdateGroupSettingsMutationOptions(options));
};
