/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */

import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  BodyType,
  ErrorType,
} from '../../config/clients/custom-http-client';
import { customInstance } from '../../config/clients/custom-http-client';
import type {
  CallbackGoogleParams,
  GetCsrfToken200,
  GetSession200,
  SignInEmail200,
  SignInEmailBody,
  SignInSocial200,
  SignInSocialBody,
  SignOut200,
  SignUpEmail200,
  SignUpEmailBody,
} from './types';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Register a new user using email and password
 * @summary Sign up with email
 */
export const signUpEmail = (
  signUpEmailBody: BodyType<SignUpEmailBody>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<SignUpEmail200>(
    {
      url: `/api/auth/sign-up/email`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: signUpEmailBody,
      signal,
    },
    options,
  );
};

export const getSignUpEmailMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof signUpEmail>>,
    TError,
    { data: BodyType<SignUpEmailBody> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof signUpEmail>>,
  TError,
  { data: BodyType<SignUpEmailBody> },
  TContext
> => {
  const mutationKey = ['signUpEmail'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof signUpEmail>>,
    { data: BodyType<SignUpEmailBody> }
  > = (props) => {
    const { data } = props ?? {};

    return signUpEmail(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SignUpEmailMutationResult = NonNullable<
  Awaited<ReturnType<typeof signUpEmail>>
>;
export type SignUpEmailMutationBody = BodyType<SignUpEmailBody>;
export type SignUpEmailMutationError = ErrorType<unknown>;

/**
 * @summary Sign up with email
 */
export const useSignUpEmail = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof signUpEmail>>,
    TError,
    { data: BodyType<SignUpEmailBody> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof signUpEmail>>,
  TError,
  { data: BodyType<SignUpEmailBody> },
  TContext
> => {
  return useMutation(getSignUpEmailMutationOptions(options));
};
/**
 * Authenticate a user using email and password
 * @summary Sign in with email
 */
export const signInEmail = (
  signInEmailBody: BodyType<SignInEmailBody>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<SignInEmail200>(
    {
      url: `/api/auth/sign-in/email`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: signInEmailBody,
      signal,
    },
    options,
  );
};

export const getSignInEmailMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof signInEmail>>,
    TError,
    { data: BodyType<SignInEmailBody> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof signInEmail>>,
  TError,
  { data: BodyType<SignInEmailBody> },
  TContext
> => {
  const mutationKey = ['signInEmail'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof signInEmail>>,
    { data: BodyType<SignInEmailBody> }
  > = (props) => {
    const { data } = props ?? {};

    return signInEmail(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SignInEmailMutationResult = NonNullable<
  Awaited<ReturnType<typeof signInEmail>>
>;
export type SignInEmailMutationBody = BodyType<SignInEmailBody>;
export type SignInEmailMutationError = ErrorType<unknown>;

/**
 * @summary Sign in with email
 */
export const useSignInEmail = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof signInEmail>>,
    TError,
    { data: BodyType<SignInEmailBody> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof signInEmail>>,
  TError,
  { data: BodyType<SignInEmailBody> },
  TContext
> => {
  return useMutation(getSignInEmailMutationOptions(options));
};
/**
 * Initiate social login flow (e.g., Google)
 * @summary Social Sign In
 */
export const signInSocial = (
  signInSocialBody: BodyType<SignInSocialBody>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<SignInSocial200>(
    {
      url: `/api/auth/sign-in/social`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: signInSocialBody,
      signal,
    },
    options,
  );
};

export const getSignInSocialMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof signInSocial>>,
    TError,
    { data: BodyType<SignInSocialBody> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof signInSocial>>,
  TError,
  { data: BodyType<SignInSocialBody> },
  TContext
> => {
  const mutationKey = ['signInSocial'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof signInSocial>>,
    { data: BodyType<SignInSocialBody> }
  > = (props) => {
    const { data } = props ?? {};

    return signInSocial(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SignInSocialMutationResult = NonNullable<
  Awaited<ReturnType<typeof signInSocial>>
>;
export type SignInSocialMutationBody = BodyType<SignInSocialBody>;
export type SignInSocialMutationError = ErrorType<unknown>;

/**
 * @summary Social Sign In
 */
export const useSignInSocial = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof signInSocial>>,
    TError,
    { data: BodyType<SignInSocialBody> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof signInSocial>>,
  TError,
  { data: BodyType<SignInSocialBody> },
  TContext
> => {
  return useMutation(getSignInSocialMutationOptions(options));
};
/**
 * Invalidate the current session
 * @summary Sign out
 */
export const signOut = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<SignOut200>(
    { url: `/api/auth/sign-out`, method: 'POST', signal },
    options,
  );
};

export const getSignOutMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof signOut>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof signOut>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['signOut'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof signOut>>,
    void
  > = () => {
    return signOut(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SignOutMutationResult = NonNullable<
  Awaited<ReturnType<typeof signOut>>
>;

export type SignOutMutationError = ErrorType<unknown>;

/**
 * @summary Sign out
 */
export const useSignOut = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof signOut>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof signOut>>,
  TError,
  void,
  TContext
> => {
  return useMutation(getSignOutMutationOptions(options));
};
/**
 * Get the current user session information
 * @summary Get session
 */
export const getSession = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<GetSession200>(
    { url: `/api/auth/get-session`, method: 'GET', signal },
    options,
  );
};

export const getGetSessionQueryKey = () => {
  return [`/api/auth/get-session`] as const;
};

export const getGetSessionQueryOptions = <
  TData = Awaited<ReturnType<typeof getSession>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getSession>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetSessionQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getSession>>> = ({
    signal,
  }) => getSession(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getSession>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetSessionQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSession>>
>;
export type GetSessionQueryError = ErrorType<unknown>;

/**
 * @summary Get session
 */

export function useGetSession<
  TData = Awaited<ReturnType<typeof getSession>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getSession>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetSessionQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Handle Google social login callback
 * @summary Google Callback
 */
export const callbackGoogle = (
  params?: CallbackGoogleParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<void>(
    { url: `/api/auth/callback/google`, method: 'GET', params, signal },
    options,
  );
};

export const getCallbackGoogleQueryKey = (params?: CallbackGoogleParams) => {
  return [`/api/auth/callback/google`, ...(params ? [params] : [])] as const;
};

export const getCallbackGoogleQueryOptions = <
  TData = Awaited<ReturnType<typeof callbackGoogle>>,
  TError = ErrorType<unknown>,
>(
  params?: CallbackGoogleParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof callbackGoogle>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getCallbackGoogleQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof callbackGoogle>>> = ({
    signal,
  }) => callbackGoogle(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof callbackGoogle>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type CallbackGoogleQueryResult = NonNullable<
  Awaited<ReturnType<typeof callbackGoogle>>
>;
export type CallbackGoogleQueryError = ErrorType<unknown>;

/**
 * @summary Google Callback
 */

export function useCallbackGoogle<
  TData = Awaited<ReturnType<typeof callbackGoogle>>,
  TError = ErrorType<unknown>,
>(
  params?: CallbackGoogleParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof callbackGoogle>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getCallbackGoogleQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Get the current CSRF token
 * @summary CSRF Token
 */
export const getCsrfToken = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<GetCsrfToken200>(
    { url: `/api/auth/csrf`, method: 'GET', signal },
    options,
  );
};

export const getGetCsrfTokenQueryKey = () => {
  return [`/api/auth/csrf`] as const;
};

export const getGetCsrfTokenQueryOptions = <
  TData = Awaited<ReturnType<typeof getCsrfToken>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getCsrfToken>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetCsrfTokenQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCsrfToken>>> = ({
    signal,
  }) => getCsrfToken(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getCsrfToken>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetCsrfTokenQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCsrfToken>>
>;
export type GetCsrfTokenQueryError = ErrorType<unknown>;

/**
 * @summary CSRF Token
 */

export function useGetCsrfToken<
  TData = Awaited<ReturnType<typeof getCsrfToken>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getCsrfToken>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetCsrfTokenQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}
