/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */

import type {
  MutationFunction,
  UseMutationOptions,
  UseMutationResult,
} from '@tanstack/react-query';
import { useMutation } from '@tanstack/react-query';
import type {
  BodyType,
  ErrorType,
} from '../../config/clients/custom-http-client';
import { customInstance } from '../../config/clients/custom-http-client';
import type {
  AddProductToCart200,
  AddProductToCart401,
  AddProductToCart404,
  AddProductToCart422,
  AddProductToCart500,
  AddProductToCartBody,
  RemoveProductFromCart401,
  RemoveProductFromCart404,
  RemoveProductFromCart422,
  RemoveProductFromCart500,
  UpdateProductInCart401,
  UpdateProductInCart404,
  UpdateProductInCart422,
  UpdateProductInCart500,
  UpdateProductInCartBody,
} from './types';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Add a product to the cart
 * @summary Adicionar produto
 */
export const addProductToCart = (
  shoppingEventId: string,
  addProductToCartBody: BodyType<AddProductToCartBody>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<AddProductToCart200>(
    {
      url: `/api/cart/add-product/${shoppingEventId}`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: addProductToCartBody,
      signal,
    },
    options,
  );
};

export const getAddProductToCartMutationOptions = <
  TError = ErrorType<
    | AddProductToCart401
    | AddProductToCart404
    | AddProductToCart422
    | AddProductToCart500
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof addProductToCart>>,
    TError,
    { shoppingEventId: string; data: BodyType<AddProductToCartBody> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof addProductToCart>>,
  TError,
  { shoppingEventId: string; data: BodyType<AddProductToCartBody> },
  TContext
> => {
  const mutationKey = ['addProductToCart'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof addProductToCart>>,
    { shoppingEventId: string; data: BodyType<AddProductToCartBody> }
  > = (props) => {
    const { shoppingEventId, data } = props ?? {};

    return addProductToCart(shoppingEventId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AddProductToCartMutationResult = NonNullable<
  Awaited<ReturnType<typeof addProductToCart>>
>;
export type AddProductToCartMutationBody = BodyType<AddProductToCartBody>;
export type AddProductToCartMutationError = ErrorType<
  | AddProductToCart401
  | AddProductToCart404
  | AddProductToCart422
  | AddProductToCart500
>;

/**
 * @summary Adicionar produto
 */
export const useAddProductToCart = <
  TError = ErrorType<
    | AddProductToCart401
    | AddProductToCart404
    | AddProductToCart422
    | AddProductToCart500
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof addProductToCart>>,
    TError,
    { shoppingEventId: string; data: BodyType<AddProductToCartBody> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof addProductToCart>>,
  TError,
  { shoppingEventId: string; data: BodyType<AddProductToCartBody> },
  TContext
> => {
  return useMutation(getAddProductToCartMutationOptions(options));
};
/**
 * Update a product in the cart
 * @summary Atualizar produto
 */
export const updateProductInCart = (
  shoppingEventId: string,
  productId: string,
  updateProductInCartBody: BodyType<UpdateProductInCartBody>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<unknown>(
    {
      url: `/api/cart/${shoppingEventId}/update-product/${productId}`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: updateProductInCartBody,
      signal,
    },
    options,
  );
};

export const getUpdateProductInCartMutationOptions = <
  TError = ErrorType<
    | UpdateProductInCart401
    | UpdateProductInCart404
    | UpdateProductInCart422
    | UpdateProductInCart500
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateProductInCart>>,
    TError,
    {
      shoppingEventId: string;
      productId: string;
      data: BodyType<UpdateProductInCartBody>;
    },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateProductInCart>>,
  TError,
  {
    shoppingEventId: string;
    productId: string;
    data: BodyType<UpdateProductInCartBody>;
  },
  TContext
> => {
  const mutationKey = ['updateProductInCart'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateProductInCart>>,
    {
      shoppingEventId: string;
      productId: string;
      data: BodyType<UpdateProductInCartBody>;
    }
  > = (props) => {
    const { shoppingEventId, productId, data } = props ?? {};

    return updateProductInCart(
      shoppingEventId,
      productId,
      data,
      requestOptions,
    );
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateProductInCartMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateProductInCart>>
>;
export type UpdateProductInCartMutationBody = BodyType<UpdateProductInCartBody>;
export type UpdateProductInCartMutationError = ErrorType<
  | UpdateProductInCart401
  | UpdateProductInCart404
  | UpdateProductInCart422
  | UpdateProductInCart500
>;

/**
 * @summary Atualizar produto
 */
export const useUpdateProductInCart = <
  TError = ErrorType<
    | UpdateProductInCart401
    | UpdateProductInCart404
    | UpdateProductInCart422
    | UpdateProductInCart500
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateProductInCart>>,
    TError,
    {
      shoppingEventId: string;
      productId: string;
      data: BodyType<UpdateProductInCartBody>;
    },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof updateProductInCart>>,
  TError,
  {
    shoppingEventId: string;
    productId: string;
    data: BodyType<UpdateProductInCartBody>;
  },
  TContext
> => {
  return useMutation(getUpdateProductInCartMutationOptions(options));
};
/**
 * Remove a product from the cart
 * @summary Remover produto
 */
export const removeProductFromCart = (
  shoppingEventId: string,
  productId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<unknown>(
    {
      url: `/api/cart/${shoppingEventId}/remove-product/${productId}`,
      method: 'DELETE',
      signal,
    },
    options,
  );
};

export const getRemoveProductFromCartMutationOptions = <
  TError = ErrorType<
    | RemoveProductFromCart401
    | RemoveProductFromCart404
    | RemoveProductFromCart422
    | RemoveProductFromCart500
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof removeProductFromCart>>,
    TError,
    { shoppingEventId: string; productId: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof removeProductFromCart>>,
  TError,
  { shoppingEventId: string; productId: string },
  TContext
> => {
  const mutationKey = ['removeProductFromCart'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof removeProductFromCart>>,
    { shoppingEventId: string; productId: string }
  > = (props) => {
    const { shoppingEventId, productId } = props ?? {};

    return removeProductFromCart(shoppingEventId, productId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RemoveProductFromCartMutationResult = NonNullable<
  Awaited<ReturnType<typeof removeProductFromCart>>
>;

export type RemoveProductFromCartMutationError = ErrorType<
  | RemoveProductFromCart401
  | RemoveProductFromCart404
  | RemoveProductFromCart422
  | RemoveProductFromCart500
>;

/**
 * @summary Remover produto
 */
export const useRemoveProductFromCart = <
  TError = ErrorType<
    | RemoveProductFromCart401
    | RemoveProductFromCart404
    | RemoveProductFromCart422
    | RemoveProductFromCart500
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof removeProductFromCart>>,
    TError,
    { shoppingEventId: string; productId: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof removeProductFromCart>>,
  TError,
  { shoppingEventId: string; productId: string },
  TContext
> => {
  return useMutation(getRemoveProductFromCartMutationOptions(options));
};
