/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AddProductToCart200,
  AddProductToCart401,
  AddProductToCart404,
  AddProductToCart422,
  AddProductToCart500,
  AddProductToCartBody,
  RemoveProductFromCart401,
  RemoveProductFromCart404,
  RemoveProductFromCart422,
  RemoveProductFromCart500,
  ScanProduct200,
  ScanProduct401,
  ScanProduct404,
  ScanProduct500,
  SearchProduct200,
  SearchProduct401,
  SearchProduct404,
  SearchProduct500,
  SearchProductParams,
  UpdateProductInCart401,
  UpdateProductInCart404,
  UpdateProductInCart422,
  UpdateProductInCart500,
  UpdateProductInCartBody
} from './types';

import { customInstance } from '../../config/clients/custom-http-client';
import type { ErrorType , BodyType } from '../../config/clients/custom-http-client';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Escanear um produto pelo código de barras
 * @summary Escanear produto
 */
export const scanProduct = (
    barcode: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ScanProduct200>(
      {url: `/api/cart/scan/${barcode}`, method: 'GET', signal
    },
      options);
    }
  



export const getScanProductQueryKey = (barcode: string,) => {
    return [
    `/api/cart/scan/${barcode}`
    ] as const;
    }

    
export const getScanProductQueryOptions = <TData = Awaited<ReturnType<typeof scanProduct>>, TError = ErrorType<ScanProduct401 | ScanProduct404 | ScanProduct500>>(barcode: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof scanProduct>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getScanProductQueryKey(barcode);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof scanProduct>>> = ({ signal }) => scanProduct(barcode, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(barcode), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof scanProduct>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ScanProductQueryResult = NonNullable<Awaited<ReturnType<typeof scanProduct>>>
export type ScanProductQueryError = ErrorType<ScanProduct401 | ScanProduct404 | ScanProduct500>


export function useScanProduct<TData = Awaited<ReturnType<typeof scanProduct>>, TError = ErrorType<ScanProduct401 | ScanProduct404 | ScanProduct500>>(
 barcode: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof scanProduct>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof scanProduct>>,
          TError,
          Awaited<ReturnType<typeof scanProduct>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useScanProduct<TData = Awaited<ReturnType<typeof scanProduct>>, TError = ErrorType<ScanProduct401 | ScanProduct404 | ScanProduct500>>(
 barcode: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof scanProduct>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof scanProduct>>,
          TError,
          Awaited<ReturnType<typeof scanProduct>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useScanProduct<TData = Awaited<ReturnType<typeof scanProduct>>, TError = ErrorType<ScanProduct401 | ScanProduct404 | ScanProduct500>>(
 barcode: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof scanProduct>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Escanear produto
 */

export function useScanProduct<TData = Awaited<ReturnType<typeof scanProduct>>, TError = ErrorType<ScanProduct401 | ScanProduct404 | ScanProduct500>>(
 barcode: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof scanProduct>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getScanProductQueryOptions(barcode,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Pesquisar produtos pelo nome ou marca
 * @summary Pesquisar produtos
 */
export const searchProduct = (
    params: SearchProductParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<SearchProduct200>(
      {url: `/api/cart/search`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getSearchProductInfiniteQueryKey = (params?: SearchProductParams,) => {
    return [
    'infinite', `/api/cart/search`, ...(params ? [params] : [])
    ] as const;
    }

export const getSearchProductQueryKey = (params?: SearchProductParams,) => {
    return [
    `/api/cart/search`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getSearchProductInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof searchProduct>>, SearchProductParams['pageIndex']>, TError = ErrorType<SearchProduct401 | SearchProduct404 | SearchProduct500>>(params: SearchProductParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof searchProduct>>, TError, TData, QueryKey, SearchProductParams['pageIndex']>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSearchProductInfiniteQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof searchProduct>>, QueryKey, SearchProductParams['pageIndex']> = ({ signal, pageParam }) => searchProduct({...params, 'pageIndex': pageParam || params?.['pageIndex']}, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof searchProduct>>, TError, TData, QueryKey, SearchProductParams['pageIndex']> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SearchProductInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof searchProduct>>>
export type SearchProductInfiniteQueryError = ErrorType<SearchProduct401 | SearchProduct404 | SearchProduct500>


export function useSearchProductInfinite<TData = InfiniteData<Awaited<ReturnType<typeof searchProduct>>, SearchProductParams['pageIndex']>, TError = ErrorType<SearchProduct401 | SearchProduct404 | SearchProduct500>>(
 params: SearchProductParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof searchProduct>>, TError, TData, QueryKey, SearchProductParams['pageIndex']>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchProduct>>,
          TError,
          Awaited<ReturnType<typeof searchProduct>>, QueryKey
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchProductInfinite<TData = InfiniteData<Awaited<ReturnType<typeof searchProduct>>, SearchProductParams['pageIndex']>, TError = ErrorType<SearchProduct401 | SearchProduct404 | SearchProduct500>>(
 params: SearchProductParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof searchProduct>>, TError, TData, QueryKey, SearchProductParams['pageIndex']>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchProduct>>,
          TError,
          Awaited<ReturnType<typeof searchProduct>>, QueryKey
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchProductInfinite<TData = InfiniteData<Awaited<ReturnType<typeof searchProduct>>, SearchProductParams['pageIndex']>, TError = ErrorType<SearchProduct401 | SearchProduct404 | SearchProduct500>>(
 params: SearchProductParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof searchProduct>>, TError, TData, QueryKey, SearchProductParams['pageIndex']>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Pesquisar produtos
 */

export function useSearchProductInfinite<TData = InfiniteData<Awaited<ReturnType<typeof searchProduct>>, SearchProductParams['pageIndex']>, TError = ErrorType<SearchProduct401 | SearchProduct404 | SearchProduct500>>(
 params: SearchProductParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof searchProduct>>, TError, TData, QueryKey, SearchProductParams['pageIndex']>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSearchProductInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getSearchProductQueryOptions = <TData = Awaited<ReturnType<typeof searchProduct>>, TError = ErrorType<SearchProduct401 | SearchProduct404 | SearchProduct500>>(params: SearchProductParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchProduct>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSearchProductQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof searchProduct>>> = ({ signal }) => searchProduct(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof searchProduct>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SearchProductQueryResult = NonNullable<Awaited<ReturnType<typeof searchProduct>>>
export type SearchProductQueryError = ErrorType<SearchProduct401 | SearchProduct404 | SearchProduct500>


export function useSearchProduct<TData = Awaited<ReturnType<typeof searchProduct>>, TError = ErrorType<SearchProduct401 | SearchProduct404 | SearchProduct500>>(
 params: SearchProductParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchProduct>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchProduct>>,
          TError,
          Awaited<ReturnType<typeof searchProduct>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchProduct<TData = Awaited<ReturnType<typeof searchProduct>>, TError = ErrorType<SearchProduct401 | SearchProduct404 | SearchProduct500>>(
 params: SearchProductParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchProduct>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchProduct>>,
          TError,
          Awaited<ReturnType<typeof searchProduct>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchProduct<TData = Awaited<ReturnType<typeof searchProduct>>, TError = ErrorType<SearchProduct401 | SearchProduct404 | SearchProduct500>>(
 params: SearchProductParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchProduct>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Pesquisar produtos
 */

export function useSearchProduct<TData = Awaited<ReturnType<typeof searchProduct>>, TError = ErrorType<SearchProduct401 | SearchProduct404 | SearchProduct500>>(
 params: SearchProductParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchProduct>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSearchProductQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Add a product to the cart
 * @summary Adicionar produto
 */
export const addProductToCart = (
    shoppingEventId: string,
    addProductToCartBody: BodyType<AddProductToCartBody>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<AddProductToCart200>(
      {url: `/api/cart/add-product/${shoppingEventId}`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addProductToCartBody, signal
    },
      options);
    }
  


export const getAddProductToCartMutationOptions = <TError = ErrorType<AddProductToCart401 | AddProductToCart404 | AddProductToCart422 | AddProductToCart500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addProductToCart>>, TError,{shoppingEventId: string;data: BodyType<AddProductToCartBody>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof addProductToCart>>, TError,{shoppingEventId: string;data: BodyType<AddProductToCartBody>}, TContext> => {

const mutationKey = ['addProductToCart'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addProductToCart>>, {shoppingEventId: string;data: BodyType<AddProductToCartBody>}> = (props) => {
          const {shoppingEventId,data} = props ?? {};

          return  addProductToCart(shoppingEventId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type AddProductToCartMutationResult = NonNullable<Awaited<ReturnType<typeof addProductToCart>>>
    export type AddProductToCartMutationBody = BodyType<AddProductToCartBody>
    export type AddProductToCartMutationError = ErrorType<AddProductToCart401 | AddProductToCart404 | AddProductToCart422 | AddProductToCart500>

    /**
 * @summary Adicionar produto
 */
export const useAddProductToCart = <TError = ErrorType<AddProductToCart401 | AddProductToCart404 | AddProductToCart422 | AddProductToCart500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addProductToCart>>, TError,{shoppingEventId: string;data: BodyType<AddProductToCartBody>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addProductToCart>>,
        TError,
        {shoppingEventId: string;data: BodyType<AddProductToCartBody>},
        TContext
      > => {
      return useMutation(getAddProductToCartMutationOptions(options), queryClient);
    }
    /**
 * Update a product in the cart
 * @summary Atualizar produto
 */
export const updateProductInCart = (
    shoppingEventId: string,
    productId: string,
    updateProductInCartBody: BodyType<UpdateProductInCartBody>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/cart/${shoppingEventId}/update-product/${productId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateProductInCartBody, signal
    },
      options);
    }
  


export const getUpdateProductInCartMutationOptions = <TError = ErrorType<UpdateProductInCart401 | UpdateProductInCart404 | UpdateProductInCart422 | UpdateProductInCart500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateProductInCart>>, TError,{shoppingEventId: string;productId: string;data: BodyType<UpdateProductInCartBody>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateProductInCart>>, TError,{shoppingEventId: string;productId: string;data: BodyType<UpdateProductInCartBody>}, TContext> => {

const mutationKey = ['updateProductInCart'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateProductInCart>>, {shoppingEventId: string;productId: string;data: BodyType<UpdateProductInCartBody>}> = (props) => {
          const {shoppingEventId,productId,data} = props ?? {};

          return  updateProductInCart(shoppingEventId,productId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateProductInCartMutationResult = NonNullable<Awaited<ReturnType<typeof updateProductInCart>>>
    export type UpdateProductInCartMutationBody = BodyType<UpdateProductInCartBody>
    export type UpdateProductInCartMutationError = ErrorType<UpdateProductInCart401 | UpdateProductInCart404 | UpdateProductInCart422 | UpdateProductInCart500>

    /**
 * @summary Atualizar produto
 */
export const useUpdateProductInCart = <TError = ErrorType<UpdateProductInCart401 | UpdateProductInCart404 | UpdateProductInCart422 | UpdateProductInCart500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateProductInCart>>, TError,{shoppingEventId: string;productId: string;data: BodyType<UpdateProductInCartBody>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateProductInCart>>,
        TError,
        {shoppingEventId: string;productId: string;data: BodyType<UpdateProductInCartBody>},
        TContext
      > => {
      return useMutation(getUpdateProductInCartMutationOptions(options), queryClient);
    }
    /**
 * Remove a product from the cart
 * @summary Remover produto
 */
export const removeProductFromCart = (
    shoppingEventId: string,
    productId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/cart/${shoppingEventId}/remove-product/${productId}`, method: 'DELETE', signal
    },
      options);
    }
  


export const getRemoveProductFromCartMutationOptions = <TError = ErrorType<RemoveProductFromCart401 | RemoveProductFromCart404 | RemoveProductFromCart422 | RemoveProductFromCart500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeProductFromCart>>, TError,{shoppingEventId: string;productId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof removeProductFromCart>>, TError,{shoppingEventId: string;productId: string}, TContext> => {

const mutationKey = ['removeProductFromCart'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof removeProductFromCart>>, {shoppingEventId: string;productId: string}> = (props) => {
          const {shoppingEventId,productId} = props ?? {};

          return  removeProductFromCart(shoppingEventId,productId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type RemoveProductFromCartMutationResult = NonNullable<Awaited<ReturnType<typeof removeProductFromCart>>>
    
    export type RemoveProductFromCartMutationError = ErrorType<RemoveProductFromCart401 | RemoveProductFromCart404 | RemoveProductFromCart422 | RemoveProductFromCart500>

    /**
 * @summary Remover produto
 */
export const useRemoveProductFromCart = <TError = ErrorType<RemoveProductFromCart401 | RemoveProductFromCart404 | RemoveProductFromCart422 | RemoveProductFromCart500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeProductFromCart>>, TError,{shoppingEventId: string;productId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof removeProductFromCart>>,
        TError,
        {shoppingEventId: string;productId: string},
        TContext
      > => {
      return useMutation(getRemoveProductFromCartMutationOptions(options), queryClient);
    }
    