/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */

import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  BodyType,
  ErrorType,
} from '../../config/clients/custom-http-client';
import { customInstance } from '../../config/clients/custom-http-client';
import type {
  CreateFamily201,
  CreateFamily401,
  CreateFamily404,
  CreateFamily409,
  CreateFamily500,
  CreateFamilyBody,
  GetFamily200,
  GetFamily400,
  GetFamily401,
  GetFamily404,
  GetFamily500,
  JoinFamily400,
  JoinFamily401,
  JoinFamily404,
  JoinFamily409,
  JoinFamily500,
  JoinFamilyBody,
  LeaveFamily400,
  LeaveFamily401,
  LeaveFamily404,
  LeaveFamily500,
  RemoveFamilyMember400,
  RemoveFamilyMember401,
  RemoveFamilyMember404,
  RemoveFamilyMember500,
} from './types';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Get the family of the current user
 * @summary Obter família
 */
export const getFamily = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<GetFamily200>(
    { url: `/api/family`, method: 'GET', signal },
    options,
  );
};

export const getGetFamilyQueryKey = () => {
  return [`/api/family`] as const;
};

export const getGetFamilyQueryOptions = <
  TData = Awaited<ReturnType<typeof getFamily>>,
  TError = ErrorType<GetFamily400 | GetFamily401 | GetFamily404 | GetFamily500>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getFamily>>, TError, TData>;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetFamilyQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getFamily>>> = ({
    signal,
  }) => getFamily(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getFamily>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetFamilyQueryResult = NonNullable<
  Awaited<ReturnType<typeof getFamily>>
>;
export type GetFamilyQueryError = ErrorType<
  GetFamily400 | GetFamily401 | GetFamily404 | GetFamily500
>;

/**
 * @summary Obter família
 */

export function useGetFamily<
  TData = Awaited<ReturnType<typeof getFamily>>,
  TError = ErrorType<GetFamily400 | GetFamily401 | GetFamily404 | GetFamily500>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getFamily>>, TError, TData>;
  request?: SecondParameter<typeof customInstance>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetFamilyQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Create a new family
 * @summary Criar família
 */
export const createFamily = (
  createFamilyBody: BodyType<CreateFamilyBody>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<CreateFamily201>(
    {
      url: `/api/family`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createFamilyBody,
      signal,
    },
    options,
  );
};

export const getCreateFamilyMutationOptions = <
  TError = ErrorType<
    CreateFamily401 | CreateFamily404 | CreateFamily409 | CreateFamily500
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createFamily>>,
    TError,
    { data: BodyType<CreateFamilyBody> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createFamily>>,
  TError,
  { data: BodyType<CreateFamilyBody> },
  TContext
> => {
  const mutationKey = ['createFamily'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createFamily>>,
    { data: BodyType<CreateFamilyBody> }
  > = (props) => {
    const { data } = props ?? {};

    return createFamily(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateFamilyMutationResult = NonNullable<
  Awaited<ReturnType<typeof createFamily>>
>;
export type CreateFamilyMutationBody = BodyType<CreateFamilyBody>;
export type CreateFamilyMutationError = ErrorType<
  CreateFamily401 | CreateFamily404 | CreateFamily409 | CreateFamily500
>;

/**
 * @summary Criar família
 */
export const useCreateFamily = <
  TError = ErrorType<
    CreateFamily401 | CreateFamily404 | CreateFamily409 | CreateFamily500
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createFamily>>,
    TError,
    { data: BodyType<CreateFamilyBody> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof createFamily>>,
  TError,
  { data: BodyType<CreateFamilyBody> },
  TContext
> => {
  return useMutation(getCreateFamilyMutationOptions(options));
};
/**
 * Join a family
 * @summary Entrar em uma família
 */
export const joinFamily = (
  joinFamilyBody: BodyType<JoinFamilyBody>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<unknown>(
    {
      url: `/api/family/members/join`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: joinFamilyBody,
      signal,
    },
    options,
  );
};

export const getJoinFamilyMutationOptions = <
  TError = ErrorType<
    | JoinFamily400
    | JoinFamily401
    | JoinFamily404
    | JoinFamily409
    | JoinFamily500
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof joinFamily>>,
    TError,
    { data: BodyType<JoinFamilyBody> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof joinFamily>>,
  TError,
  { data: BodyType<JoinFamilyBody> },
  TContext
> => {
  const mutationKey = ['joinFamily'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof joinFamily>>,
    { data: BodyType<JoinFamilyBody> }
  > = (props) => {
    const { data } = props ?? {};

    return joinFamily(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type JoinFamilyMutationResult = NonNullable<
  Awaited<ReturnType<typeof joinFamily>>
>;
export type JoinFamilyMutationBody = BodyType<JoinFamilyBody>;
export type JoinFamilyMutationError = ErrorType<
  JoinFamily400 | JoinFamily401 | JoinFamily404 | JoinFamily409 | JoinFamily500
>;

/**
 * @summary Entrar em uma família
 */
export const useJoinFamily = <
  TError = ErrorType<
    | JoinFamily400
    | JoinFamily401
    | JoinFamily404
    | JoinFamily409
    | JoinFamily500
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof joinFamily>>,
    TError,
    { data: BodyType<JoinFamilyBody> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof joinFamily>>,
  TError,
  { data: BodyType<JoinFamilyBody> },
  TContext
> => {
  return useMutation(getJoinFamilyMutationOptions(options));
};
/**
 * Leave a family
 * @summary Sair da família
 */
export const leaveFamily = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<unknown>(
    { url: `/api/family/members/leave`, method: 'PUT', signal },
    options,
  );
};

export const getLeaveFamilyMutationOptions = <
  TError = ErrorType<
    LeaveFamily400 | LeaveFamily401 | LeaveFamily404 | LeaveFamily500
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof leaveFamily>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof leaveFamily>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['leaveFamily'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof leaveFamily>>,
    void
  > = () => {
    return leaveFamily(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type LeaveFamilyMutationResult = NonNullable<
  Awaited<ReturnType<typeof leaveFamily>>
>;

export type LeaveFamilyMutationError = ErrorType<
  LeaveFamily400 | LeaveFamily401 | LeaveFamily404 | LeaveFamily500
>;

/**
 * @summary Sair da família
 */
export const useLeaveFamily = <
  TError = ErrorType<
    LeaveFamily400 | LeaveFamily401 | LeaveFamily404 | LeaveFamily500
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof leaveFamily>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof leaveFamily>>,
  TError,
  void,
  TContext
> => {
  return useMutation(getLeaveFamilyMutationOptions(options));
};
/**
 * Remove a family member
 * @summary Remover membro
 */
export const removeFamilyMember = (
  memberId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<unknown>(
    { url: `/api/family/members/remove/${memberId}`, method: 'DELETE', signal },
    options,
  );
};

export const getRemoveFamilyMemberMutationOptions = <
  TError = ErrorType<
    | RemoveFamilyMember400
    | RemoveFamilyMember401
    | RemoveFamilyMember404
    | RemoveFamilyMember500
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof removeFamilyMember>>,
    TError,
    { memberId: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof removeFamilyMember>>,
  TError,
  { memberId: string },
  TContext
> => {
  const mutationKey = ['removeFamilyMember'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof removeFamilyMember>>,
    { memberId: string }
  > = (props) => {
    const { memberId } = props ?? {};

    return removeFamilyMember(memberId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RemoveFamilyMemberMutationResult = NonNullable<
  Awaited<ReturnType<typeof removeFamilyMember>>
>;

export type RemoveFamilyMemberMutationError = ErrorType<
  | RemoveFamilyMember400
  | RemoveFamilyMember401
  | RemoveFamilyMember404
  | RemoveFamilyMember500
>;

/**
 * @summary Remover membro
 */
export const useRemoveFamilyMember = <
  TError = ErrorType<
    | RemoveFamilyMember400
    | RemoveFamilyMember401
    | RemoveFamilyMember404
    | RemoveFamilyMember500
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof removeFamilyMember>>,
    TError,
    { memberId: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof removeFamilyMember>>,
  TError,
  { memberId: string },
  TContext
> => {
  return useMutation(getRemoveFamilyMemberMutationOptions(options));
};
