/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */

import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  BodyType,
  ErrorType,
} from '../../config/clients/custom-http-client';
import { customInstance } from '../../config/clients/custom-http-client';
import type {
  CreateGroup201,
  CreateGroup401,
  CreateGroup404,
  CreateGroup500,
  CreateGroupBody,
  DeleteGroup401,
  DeleteGroup403,
  DeleteGroup500,
  GetGroups200Item,
  GetInviteInfo200,
  GetInviteInfo401,
  GetInviteInfo403,
  GetInviteInfo500,
  JoinGroup400,
  JoinGroup401,
  JoinGroup404,
  JoinGroup500,
  JoinGroupBody,
  LeaveGroup400,
  LeaveGroup401,
  LeaveGroup403,
  LeaveGroup500,
  RegenerateInviteCode200,
  RegenerateInviteCode401,
  RegenerateInviteCode403,
  RegenerateInviteCode500,
  RemoveMember401,
  RemoveMember403,
  RemoveMember500,
  UpdateGroup200,
  UpdateGroup401,
  UpdateGroup403,
  UpdateGroup500,
  UpdateGroupBody,
  UpdateMemberRole401,
  UpdateMemberRole403,
  UpdateMemberRole500,
  UpdateMemberRoleBody,
} from './types';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Get all groups the current user belongs to
 * @summary Listar grupos
 */
export const getGroups = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<GetGroups200Item[]>(
    { url: `/api/group`, method: 'GET', signal },
    options,
  );
};

export const getGetGroupsQueryKey = () => {
  return [`/api/group`] as const;
};

export const getGetGroupsQueryOptions = <
  TData = Awaited<ReturnType<typeof getGroups>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getGroups>>, TError, TData>;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetGroupsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getGroups>>> = ({
    signal,
  }) => getGroups(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getGroups>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetGroupsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getGroups>>
>;
export type GetGroupsQueryError = ErrorType<unknown>;

/**
 * @summary Listar grupos
 */

export function useGetGroups<
  TData = Awaited<ReturnType<typeof getGroups>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getGroups>>, TError, TData>;
  request?: SecondParameter<typeof customInstance>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetGroupsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Create a new collaboration group
 * @summary Criar grupo
 */
export const createGroup = (
  createGroupBody: BodyType<CreateGroupBody>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<CreateGroup201>(
    {
      url: `/api/group`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createGroupBody,
      signal,
    },
    options,
  );
};

export const getCreateGroupMutationOptions = <
  TError = ErrorType<CreateGroup401 | CreateGroup404 | CreateGroup500>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createGroup>>,
    TError,
    { data: BodyType<CreateGroupBody> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createGroup>>,
  TError,
  { data: BodyType<CreateGroupBody> },
  TContext
> => {
  const mutationKey = ['createGroup'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createGroup>>,
    { data: BodyType<CreateGroupBody> }
  > = (props) => {
    const { data } = props ?? {};

    return createGroup(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateGroupMutationResult = NonNullable<
  Awaited<ReturnType<typeof createGroup>>
>;
export type CreateGroupMutationBody = BodyType<CreateGroupBody>;
export type CreateGroupMutationError = ErrorType<
  CreateGroup401 | CreateGroup404 | CreateGroup500
>;

/**
 * @summary Criar grupo
 */
export const useCreateGroup = <
  TError = ErrorType<CreateGroup401 | CreateGroup404 | CreateGroup500>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createGroup>>,
    TError,
    { data: BodyType<CreateGroupBody> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof createGroup>>,
  TError,
  { data: BodyType<CreateGroupBody> },
  TContext
> => {
  return useMutation(getCreateGroupMutationOptions(options));
};
/**
 * Join a group using an invite code
 * @summary Entrar no grupo
 */
export const joinGroup = (
  joinGroupBody: BodyType<JoinGroupBody>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<unknown>(
    {
      url: `/api/group/join`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: joinGroupBody,
      signal,
    },
    options,
  );
};

export const getJoinGroupMutationOptions = <
  TError = ErrorType<JoinGroup400 | JoinGroup401 | JoinGroup404 | JoinGroup500>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof joinGroup>>,
    TError,
    { data: BodyType<JoinGroupBody> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof joinGroup>>,
  TError,
  { data: BodyType<JoinGroupBody> },
  TContext
> => {
  const mutationKey = ['joinGroup'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof joinGroup>>,
    { data: BodyType<JoinGroupBody> }
  > = (props) => {
    const { data } = props ?? {};

    return joinGroup(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type JoinGroupMutationResult = NonNullable<
  Awaited<ReturnType<typeof joinGroup>>
>;
export type JoinGroupMutationBody = BodyType<JoinGroupBody>;
export type JoinGroupMutationError = ErrorType<
  JoinGroup400 | JoinGroup401 | JoinGroup404 | JoinGroup500
>;

/**
 * @summary Entrar no grupo
 */
export const useJoinGroup = <
  TError = ErrorType<JoinGroup400 | JoinGroup401 | JoinGroup404 | JoinGroup500>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof joinGroup>>,
    TError,
    { data: BodyType<JoinGroupBody> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof joinGroup>>,
  TError,
  { data: BodyType<JoinGroupBody> },
  TContext
> => {
  return useMutation(getJoinGroupMutationOptions(options));
};
/**
 * Leave a collaboration group
 * @summary Sair do grupo
 */
export const leaveGroup = (
  groupId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<unknown>(
    { url: `/api/group/${groupId}/leave`, method: 'POST', signal },
    options,
  );
};

export const getLeaveGroupMutationOptions = <
  TError = ErrorType<
    LeaveGroup400 | LeaveGroup401 | LeaveGroup403 | LeaveGroup500
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof leaveGroup>>,
    TError,
    { groupId: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof leaveGroup>>,
  TError,
  { groupId: string },
  TContext
> => {
  const mutationKey = ['leaveGroup'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof leaveGroup>>,
    { groupId: string }
  > = (props) => {
    const { groupId } = props ?? {};

    return leaveGroup(groupId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type LeaveGroupMutationResult = NonNullable<
  Awaited<ReturnType<typeof leaveGroup>>
>;

export type LeaveGroupMutationError = ErrorType<
  LeaveGroup400 | LeaveGroup401 | LeaveGroup403 | LeaveGroup500
>;

/**
 * @summary Sair do grupo
 */
export const useLeaveGroup = <
  TError = ErrorType<
    LeaveGroup400 | LeaveGroup401 | LeaveGroup403 | LeaveGroup500
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof leaveGroup>>,
    TError,
    { groupId: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof leaveGroup>>,
  TError,
  { groupId: string },
  TContext
> => {
  return useMutation(getLeaveGroupMutationOptions(options));
};
/**
 * Remove a member from the group (RBAC required)
 * @summary Remover membro
 */
export const removeMember = (
  groupId: string,
  memberId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<unknown>(
    {
      url: `/api/group/${groupId}/members/${memberId}`,
      method: 'DELETE',
      signal,
    },
    options,
  );
};

export const getRemoveMemberMutationOptions = <
  TError = ErrorType<RemoveMember401 | RemoveMember403 | RemoveMember500>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof removeMember>>,
    TError,
    { groupId: string; memberId: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof removeMember>>,
  TError,
  { groupId: string; memberId: string },
  TContext
> => {
  const mutationKey = ['removeMember'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof removeMember>>,
    { groupId: string; memberId: string }
  > = (props) => {
    const { groupId, memberId } = props ?? {};

    return removeMember(groupId, memberId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RemoveMemberMutationResult = NonNullable<
  Awaited<ReturnType<typeof removeMember>>
>;

export type RemoveMemberMutationError = ErrorType<
  RemoveMember401 | RemoveMember403 | RemoveMember500
>;

/**
 * @summary Remover membro
 */
export const useRemoveMember = <
  TError = ErrorType<RemoveMember401 | RemoveMember403 | RemoveMember500>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof removeMember>>,
    TError,
    { groupId: string; memberId: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof removeMember>>,
  TError,
  { groupId: string; memberId: string },
  TContext
> => {
  return useMutation(getRemoveMemberMutationOptions(options));
};
/**
 * Update a member's role (RBAC required)
 * @summary Alterar cargo
 */
export const updateMemberRole = (
  groupId: string,
  memberId: string,
  updateMemberRoleBody: BodyType<UpdateMemberRoleBody>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<unknown>(
    {
      url: `/api/group/${groupId}/members/${memberId}/role`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: updateMemberRoleBody,
      signal,
    },
    options,
  );
};

export const getUpdateMemberRoleMutationOptions = <
  TError = ErrorType<
    UpdateMemberRole401 | UpdateMemberRole403 | UpdateMemberRole500
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateMemberRole>>,
    TError,
    { groupId: string; memberId: string; data: BodyType<UpdateMemberRoleBody> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateMemberRole>>,
  TError,
  { groupId: string; memberId: string; data: BodyType<UpdateMemberRoleBody> },
  TContext
> => {
  const mutationKey = ['updateMemberRole'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateMemberRole>>,
    { groupId: string; memberId: string; data: BodyType<UpdateMemberRoleBody> }
  > = (props) => {
    const { groupId, memberId, data } = props ?? {};

    return updateMemberRole(groupId, memberId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateMemberRoleMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateMemberRole>>
>;
export type UpdateMemberRoleMutationBody = BodyType<UpdateMemberRoleBody>;
export type UpdateMemberRoleMutationError = ErrorType<
  UpdateMemberRole401 | UpdateMemberRole403 | UpdateMemberRole500
>;

/**
 * @summary Alterar cargo
 */
export const useUpdateMemberRole = <
  TError = ErrorType<
    UpdateMemberRole401 | UpdateMemberRole403 | UpdateMemberRole500
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateMemberRole>>,
    TError,
    { groupId: string; memberId: string; data: BodyType<UpdateMemberRoleBody> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof updateMemberRole>>,
  TError,
  { groupId: string; memberId: string; data: BodyType<UpdateMemberRoleBody> },
  TContext
> => {
  return useMutation(getUpdateMemberRoleMutationOptions(options));
};
/**
 * Get invitation magic link and QR information
 * @summary Obter convite
 */
export const getInviteInfo = (
  groupId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<GetInviteInfo200>(
    { url: `/api/group/${groupId}/invite`, method: 'GET', signal },
    options,
  );
};

export const getGetInviteInfoQueryKey = (groupId: string) => {
  return [`/api/group/${groupId}/invite`] as const;
};

export const getGetInviteInfoQueryOptions = <
  TData = Awaited<ReturnType<typeof getInviteInfo>>,
  TError = ErrorType<GetInviteInfo401 | GetInviteInfo403 | GetInviteInfo500>,
>(
  groupId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getInviteInfo>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetInviteInfoQueryKey(groupId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getInviteInfo>>> = ({
    signal,
  }) => getInviteInfo(groupId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!groupId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getInviteInfo>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetInviteInfoQueryResult = NonNullable<
  Awaited<ReturnType<typeof getInviteInfo>>
>;
export type GetInviteInfoQueryError = ErrorType<
  GetInviteInfo401 | GetInviteInfo403 | GetInviteInfo500
>;

/**
 * @summary Obter convite
 */

export function useGetInviteInfo<
  TData = Awaited<ReturnType<typeof getInviteInfo>>,
  TError = ErrorType<GetInviteInfo401 | GetInviteInfo403 | GetInviteInfo500>,
>(
  groupId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getInviteInfo>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetInviteInfoQueryOptions(groupId, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Regenerate group invitation code
 * @summary Regenerar convite
 */
export const regenerateInviteCode = (
  groupId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<RegenerateInviteCode200>(
    { url: `/api/group/${groupId}/invite/regenerate`, method: 'POST', signal },
    options,
  );
};

export const getRegenerateInviteCodeMutationOptions = <
  TError = ErrorType<
    RegenerateInviteCode401 | RegenerateInviteCode403 | RegenerateInviteCode500
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof regenerateInviteCode>>,
    TError,
    { groupId: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof regenerateInviteCode>>,
  TError,
  { groupId: string },
  TContext
> => {
  const mutationKey = ['regenerateInviteCode'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof regenerateInviteCode>>,
    { groupId: string }
  > = (props) => {
    const { groupId } = props ?? {};

    return regenerateInviteCode(groupId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RegenerateInviteCodeMutationResult = NonNullable<
  Awaited<ReturnType<typeof regenerateInviteCode>>
>;

export type RegenerateInviteCodeMutationError = ErrorType<
  RegenerateInviteCode401 | RegenerateInviteCode403 | RegenerateInviteCode500
>;

/**
 * @summary Regenerar convite
 */
export const useRegenerateInviteCode = <
  TError = ErrorType<
    RegenerateInviteCode401 | RegenerateInviteCode403 | RegenerateInviteCode500
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof regenerateInviteCode>>,
    TError,
    { groupId: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof regenerateInviteCode>>,
  TError,
  { groupId: string },
  TContext
> => {
  return useMutation(getRegenerateInviteCodeMutationOptions(options));
};
/**
 * Update group details
 * @summary Atualizar grupo
 */
export const updateGroup = (
  groupId: string,
  updateGroupBody: BodyType<UpdateGroupBody>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<UpdateGroup200>(
    {
      url: `/api/group/${groupId}`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: updateGroupBody,
      signal,
    },
    options,
  );
};

export const getUpdateGroupMutationOptions = <
  TError = ErrorType<UpdateGroup401 | UpdateGroup403 | UpdateGroup500>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateGroup>>,
    TError,
    { groupId: string; data: BodyType<UpdateGroupBody> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateGroup>>,
  TError,
  { groupId: string; data: BodyType<UpdateGroupBody> },
  TContext
> => {
  const mutationKey = ['updateGroup'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateGroup>>,
    { groupId: string; data: BodyType<UpdateGroupBody> }
  > = (props) => {
    const { groupId, data } = props ?? {};

    return updateGroup(groupId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateGroupMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateGroup>>
>;
export type UpdateGroupMutationBody = BodyType<UpdateGroupBody>;
export type UpdateGroupMutationError = ErrorType<
  UpdateGroup401 | UpdateGroup403 | UpdateGroup500
>;

/**
 * @summary Atualizar grupo
 */
export const useUpdateGroup = <
  TError = ErrorType<UpdateGroup401 | UpdateGroup403 | UpdateGroup500>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateGroup>>,
    TError,
    { groupId: string; data: BodyType<UpdateGroupBody> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof updateGroup>>,
  TError,
  { groupId: string; data: BodyType<UpdateGroupBody> },
  TContext
> => {
  return useMutation(getUpdateGroupMutationOptions(options));
};
/**
 * Delete a collaboration group
 * @summary Deletar grupo
 */
export const deleteGroup = (
  groupId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<unknown>(
    { url: `/api/group/${groupId}`, method: 'DELETE', signal },
    options,
  );
};

export const getDeleteGroupMutationOptions = <
  TError = ErrorType<DeleteGroup401 | DeleteGroup403 | DeleteGroup500>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteGroup>>,
    TError,
    { groupId: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteGroup>>,
  TError,
  { groupId: string },
  TContext
> => {
  const mutationKey = ['deleteGroup'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteGroup>>,
    { groupId: string }
  > = (props) => {
    const { groupId } = props ?? {};

    return deleteGroup(groupId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteGroupMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteGroup>>
>;

export type DeleteGroupMutationError = ErrorType<
  DeleteGroup401 | DeleteGroup403 | DeleteGroup500
>;

/**
 * @summary Deletar grupo
 */
export const useDeleteGroup = <
  TError = ErrorType<DeleteGroup401 | DeleteGroup403 | DeleteGroup500>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteGroup>>,
    TError,
    { groupId: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof deleteGroup>>,
  TError,
  { groupId: string },
  TContext
> => {
  return useMutation(getDeleteGroupMutationOptions(options));
};
