/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetMarketById200,
  GetMarketById401,
  GetMarketById404,
  GetMarketById500,
  GetMarketByIdParams,
  ListMarkets200,
  ListMarkets401,
  ListMarkets500,
  ListMarketsParams
} from './types';

import { customInstance } from '../../config/clients/custom-http-client';
import type { ErrorType } from '../../config/clients/custom-http-client';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * List all markets
 * @summary Listar mercados
 */
export const listMarkets = (
    params?: ListMarketsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ListMarkets200>(
      {url: `/api/market`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getListMarketsQueryKey = (params?: ListMarketsParams,) => {
    return [
    `/api/market`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getListMarketsQueryOptions = <TData = Awaited<ReturnType<typeof listMarkets>>, TError = ErrorType<ListMarkets401 | ListMarkets500>>(params?: ListMarketsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMarkets>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListMarketsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listMarkets>>> = ({ signal }) => listMarkets(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listMarkets>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListMarketsQueryResult = NonNullable<Awaited<ReturnType<typeof listMarkets>>>
export type ListMarketsQueryError = ErrorType<ListMarkets401 | ListMarkets500>


export function useListMarkets<TData = Awaited<ReturnType<typeof listMarkets>>, TError = ErrorType<ListMarkets401 | ListMarkets500>>(
 params: undefined |  ListMarketsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMarkets>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listMarkets>>,
          TError,
          Awaited<ReturnType<typeof listMarkets>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListMarkets<TData = Awaited<ReturnType<typeof listMarkets>>, TError = ErrorType<ListMarkets401 | ListMarkets500>>(
 params?: ListMarketsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMarkets>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listMarkets>>,
          TError,
          Awaited<ReturnType<typeof listMarkets>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListMarkets<TData = Awaited<ReturnType<typeof listMarkets>>, TError = ErrorType<ListMarkets401 | ListMarkets500>>(
 params?: ListMarketsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMarkets>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Listar mercados
 */

export function useListMarkets<TData = Awaited<ReturnType<typeof listMarkets>>, TError = ErrorType<ListMarkets401 | ListMarkets500>>(
 params?: ListMarketsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMarkets>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListMarketsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Get market by id
 * @summary Obter mercado por id
 */
export const getMarketById = (
    marketId: string,
    params?: GetMarketByIdParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetMarketById200>(
      {url: `/api/market/${marketId}`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetMarketByIdQueryKey = (marketId: string,
    params?: GetMarketByIdParams,) => {
    return [
    `/api/market/${marketId}`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetMarketByIdQueryOptions = <TData = Awaited<ReturnType<typeof getMarketById>>, TError = ErrorType<GetMarketById401 | GetMarketById404 | GetMarketById500>>(marketId: string,
    params?: GetMarketByIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMarketById>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMarketByIdQueryKey(marketId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMarketById>>> = ({ signal }) => getMarketById(marketId,params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(marketId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMarketById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMarketByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getMarketById>>>
export type GetMarketByIdQueryError = ErrorType<GetMarketById401 | GetMarketById404 | GetMarketById500>


export function useGetMarketById<TData = Awaited<ReturnType<typeof getMarketById>>, TError = ErrorType<GetMarketById401 | GetMarketById404 | GetMarketById500>>(
 marketId: string,
    params: undefined |  GetMarketByIdParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMarketById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMarketById>>,
          TError,
          Awaited<ReturnType<typeof getMarketById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMarketById<TData = Awaited<ReturnType<typeof getMarketById>>, TError = ErrorType<GetMarketById401 | GetMarketById404 | GetMarketById500>>(
 marketId: string,
    params?: GetMarketByIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMarketById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMarketById>>,
          TError,
          Awaited<ReturnType<typeof getMarketById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMarketById<TData = Awaited<ReturnType<typeof getMarketById>>, TError = ErrorType<GetMarketById401 | GetMarketById404 | GetMarketById500>>(
 marketId: string,
    params?: GetMarketByIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMarketById>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Obter mercado por id
 */

export function useGetMarketById<TData = Awaited<ReturnType<typeof getMarketById>>, TError = ErrorType<GetMarketById401 | GetMarketById404 | GetMarketById500>>(
 marketId: string,
    params?: GetMarketByIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMarketById>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMarketByIdQueryOptions(marketId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




