/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */

import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';
import { useQuery } from '@tanstack/react-query';
import type { ErrorType } from '../../config/clients/custom-http-client';
import { customInstance } from '../../config/clients/custom-http-client';
import type {
  GetMarketById200,
  GetMarketById401,
  GetMarketById404,
  GetMarketById500,
  GetMarketByIdParams,
  ListMarkets200,
  ListMarkets401,
  ListMarkets500,
  ListMarketsParams,
} from './types';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * List all markets
 * @summary Listar mercados
 */
export const listMarkets = (
  params?: ListMarketsParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ListMarkets200>(
    { url: `/api/market`, method: 'GET', params, signal },
    options,
  );
};

export const getListMarketsQueryKey = (params?: ListMarketsParams) => {
  return [`/api/market`, ...(params ? [params] : [])] as const;
};

export const getListMarketsQueryOptions = <
  TData = Awaited<ReturnType<typeof listMarkets>>,
  TError = ErrorType<ListMarkets401 | ListMarkets500>,
>(
  params?: ListMarketsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listMarkets>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListMarketsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listMarkets>>> = ({
    signal,
  }) => listMarkets(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listMarkets>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListMarketsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listMarkets>>
>;
export type ListMarketsQueryError = ErrorType<ListMarkets401 | ListMarkets500>;

/**
 * @summary Listar mercados
 */

export function useListMarkets<
  TData = Awaited<ReturnType<typeof listMarkets>>,
  TError = ErrorType<ListMarkets401 | ListMarkets500>,
>(
  params?: ListMarketsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listMarkets>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListMarketsQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Get market by id
 * @summary Obter mercado por id
 */
export const getMarketById = (
  marketId: string,
  params?: GetMarketByIdParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<GetMarketById200>(
    { url: `/api/market/${marketId}`, method: 'GET', params, signal },
    options,
  );
};

export const getGetMarketByIdQueryKey = (
  marketId: string,
  params?: GetMarketByIdParams,
) => {
  return [`/api/market/${marketId}`, ...(params ? [params] : [])] as const;
};

export const getGetMarketByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getMarketById>>,
  TError = ErrorType<GetMarketById401 | GetMarketById404 | GetMarketById500>,
>(
  marketId: string,
  params?: GetMarketByIdParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getMarketById>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetMarketByIdQueryKey(marketId, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMarketById>>> = ({
    signal,
  }) => getMarketById(marketId, params, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!marketId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getMarketById>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetMarketByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMarketById>>
>;
export type GetMarketByIdQueryError = ErrorType<
  GetMarketById401 | GetMarketById404 | GetMarketById500
>;

/**
 * @summary Obter mercado por id
 */

export function useGetMarketById<
  TData = Awaited<ReturnType<typeof getMarketById>>,
  TError = ErrorType<GetMarketById401 | GetMarketById404 | GetMarketById500>,
>(
  marketId: string,
  params?: GetMarketByIdParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getMarketById>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetMarketByIdQueryOptions(marketId, params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}
