/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */

import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';
import { useQuery } from '@tanstack/react-query';
import type { ErrorType } from '../../config/clients/custom-http-client';
import { customInstance } from '../../config/clients/custom-http-client';
import type {
  ScanProduct200,
  SearchProducts200,
  SearchProductsParams,
} from './types';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Escanear um produto pelo código de barras
 * @summary Escanear produto
 */
export const scanProduct = (
  barcode: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ScanProduct200>(
    { url: `/api/product/scan/${barcode}`, method: 'GET', signal },
    options,
  );
};

export const getScanProductQueryKey = (barcode: string) => {
  return [`/api/product/scan/${barcode}`] as const;
};

export const getScanProductQueryOptions = <
  TData = Awaited<ReturnType<typeof scanProduct>>,
  TError = ErrorType<unknown>,
>(
  barcode: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof scanProduct>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getScanProductQueryKey(barcode);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof scanProduct>>> = ({
    signal,
  }) => scanProduct(barcode, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!barcode,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof scanProduct>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ScanProductQueryResult = NonNullable<
  Awaited<ReturnType<typeof scanProduct>>
>;
export type ScanProductQueryError = ErrorType<unknown>;

/**
 * @summary Escanear produto
 */

export function useScanProduct<
  TData = Awaited<ReturnType<typeof scanProduct>>,
  TError = ErrorType<unknown>,
>(
  barcode: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof scanProduct>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getScanProductQueryOptions(barcode, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Pesquisar produtos pelo nome ou marca
 * @summary Pesquisar produtos
 */
export const searchProducts = (
  params: SearchProductsParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<SearchProducts200>(
    { url: `/api/product/search`, method: 'GET', params, signal },
    options,
  );
};

export const getSearchProductsQueryKey = (params?: SearchProductsParams) => {
  return [`/api/product/search`, ...(params ? [params] : [])] as const;
};

export const getSearchProductsQueryOptions = <
  TData = Awaited<ReturnType<typeof searchProducts>>,
  TError = ErrorType<unknown>,
>(
  params: SearchProductsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof searchProducts>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSearchProductsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof searchProducts>>> = ({
    signal,
  }) => searchProducts(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof searchProducts>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type SearchProductsQueryResult = NonNullable<
  Awaited<ReturnType<typeof searchProducts>>
>;
export type SearchProductsQueryError = ErrorType<unknown>;

/**
 * @summary Pesquisar produtos
 */

export function useSearchProducts<
  TData = Awaited<ReturnType<typeof searchProducts>>,
  TError = ErrorType<unknown>,
>(
  params: SearchProductsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof searchProducts>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getSearchProductsQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}
