/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  EndShoppingEvent200,
  EndShoppingEvent401,
  EndShoppingEvent404,
  EndShoppingEvent422,
  EndShoppingEvent500,
  EndShoppingEventBody,
  GetShoppingEventById200,
  GetShoppingEventById401,
  GetShoppingEventById404,
  GetShoppingEventById500,
  GetShoppingEventList200,
  GetShoppingEventList401,
  GetShoppingEventList404,
  GetShoppingEventList422,
  GetShoppingEventList500,
  GetShoppingEventListParams,
  StartShoppingEvent200,
  StartShoppingEvent401,
  StartShoppingEvent404,
  StartShoppingEvent500,
  StartShoppingEventBody
} from './types';

import { customInstance } from '../../config/clients/custom-http-client';
import type { ErrorType , BodyType } from '../../config/clients/custom-http-client';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Start a shopping event
 * @summary Iniciar evento de compras
 */
export const startShoppingEvent = (
    startShoppingEventBody: BodyType<StartShoppingEventBody>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<StartShoppingEvent200>(
      {url: `/api/shopping-event/start`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: startShoppingEventBody, signal
    },
      options);
    }
  


export const getStartShoppingEventMutationOptions = <TError = ErrorType<StartShoppingEvent401 | StartShoppingEvent404 | StartShoppingEvent500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof startShoppingEvent>>, TError,{data: BodyType<StartShoppingEventBody>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof startShoppingEvent>>, TError,{data: BodyType<StartShoppingEventBody>}, TContext> => {

const mutationKey = ['startShoppingEvent'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof startShoppingEvent>>, {data: BodyType<StartShoppingEventBody>}> = (props) => {
          const {data} = props ?? {};

          return  startShoppingEvent(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type StartShoppingEventMutationResult = NonNullable<Awaited<ReturnType<typeof startShoppingEvent>>>
    export type StartShoppingEventMutationBody = BodyType<StartShoppingEventBody>
    export type StartShoppingEventMutationError = ErrorType<StartShoppingEvent401 | StartShoppingEvent404 | StartShoppingEvent500>

    /**
 * @summary Iniciar evento de compras
 */
export const useStartShoppingEvent = <TError = ErrorType<StartShoppingEvent401 | StartShoppingEvent404 | StartShoppingEvent500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof startShoppingEvent>>, TError,{data: BodyType<StartShoppingEventBody>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof startShoppingEvent>>,
        TError,
        {data: BodyType<StartShoppingEventBody>},
        TContext
      > => {
      return useMutation(getStartShoppingEventMutationOptions(options), queryClient);
    }
    /**
 * End a shopping event
 * @summary Finalizar evento de compras
 */
export const endShoppingEvent = (
    shoppingEventId: string,
    endShoppingEventBody: BodyType<EndShoppingEventBody>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<EndShoppingEvent200>(
      {url: `/api/shopping-event/end/${shoppingEventId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: endShoppingEventBody, signal
    },
      options);
    }
  


export const getEndShoppingEventMutationOptions = <TError = ErrorType<EndShoppingEvent401 | EndShoppingEvent404 | EndShoppingEvent422 | EndShoppingEvent500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof endShoppingEvent>>, TError,{shoppingEventId: string;data: BodyType<EndShoppingEventBody>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof endShoppingEvent>>, TError,{shoppingEventId: string;data: BodyType<EndShoppingEventBody>}, TContext> => {

const mutationKey = ['endShoppingEvent'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof endShoppingEvent>>, {shoppingEventId: string;data: BodyType<EndShoppingEventBody>}> = (props) => {
          const {shoppingEventId,data} = props ?? {};

          return  endShoppingEvent(shoppingEventId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type EndShoppingEventMutationResult = NonNullable<Awaited<ReturnType<typeof endShoppingEvent>>>
    export type EndShoppingEventMutationBody = BodyType<EndShoppingEventBody>
    export type EndShoppingEventMutationError = ErrorType<EndShoppingEvent401 | EndShoppingEvent404 | EndShoppingEvent422 | EndShoppingEvent500>

    /**
 * @summary Finalizar evento de compras
 */
export const useEndShoppingEvent = <TError = ErrorType<EndShoppingEvent401 | EndShoppingEvent404 | EndShoppingEvent422 | EndShoppingEvent500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof endShoppingEvent>>, TError,{shoppingEventId: string;data: BodyType<EndShoppingEventBody>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof endShoppingEvent>>,
        TError,
        {shoppingEventId: string;data: BodyType<EndShoppingEventBody>},
        TContext
      > => {
      return useMutation(getEndShoppingEventMutationOptions(options), queryClient);
    }
    /**
 * Get a list of shopping events
 * @summary Listar eventos de compras
 */
export const getShoppingEventList = (
    params?: GetShoppingEventListParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetShoppingEventList200>(
      {url: `/api/shopping-event`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetShoppingEventListQueryKey = (params?: GetShoppingEventListParams,) => {
    return [
    `/api/shopping-event`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetShoppingEventListQueryOptions = <TData = Awaited<ReturnType<typeof getShoppingEventList>>, TError = ErrorType<GetShoppingEventList401 | GetShoppingEventList404 | GetShoppingEventList422 | GetShoppingEventList500>>(params?: GetShoppingEventListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getShoppingEventList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetShoppingEventListQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getShoppingEventList>>> = ({ signal }) => getShoppingEventList(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getShoppingEventList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetShoppingEventListQueryResult = NonNullable<Awaited<ReturnType<typeof getShoppingEventList>>>
export type GetShoppingEventListQueryError = ErrorType<GetShoppingEventList401 | GetShoppingEventList404 | GetShoppingEventList422 | GetShoppingEventList500>


export function useGetShoppingEventList<TData = Awaited<ReturnType<typeof getShoppingEventList>>, TError = ErrorType<GetShoppingEventList401 | GetShoppingEventList404 | GetShoppingEventList422 | GetShoppingEventList500>>(
 params: undefined |  GetShoppingEventListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getShoppingEventList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getShoppingEventList>>,
          TError,
          Awaited<ReturnType<typeof getShoppingEventList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetShoppingEventList<TData = Awaited<ReturnType<typeof getShoppingEventList>>, TError = ErrorType<GetShoppingEventList401 | GetShoppingEventList404 | GetShoppingEventList422 | GetShoppingEventList500>>(
 params?: GetShoppingEventListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getShoppingEventList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getShoppingEventList>>,
          TError,
          Awaited<ReturnType<typeof getShoppingEventList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetShoppingEventList<TData = Awaited<ReturnType<typeof getShoppingEventList>>, TError = ErrorType<GetShoppingEventList401 | GetShoppingEventList404 | GetShoppingEventList422 | GetShoppingEventList500>>(
 params?: GetShoppingEventListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getShoppingEventList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Listar eventos de compras
 */

export function useGetShoppingEventList<TData = Awaited<ReturnType<typeof getShoppingEventList>>, TError = ErrorType<GetShoppingEventList401 | GetShoppingEventList404 | GetShoppingEventList422 | GetShoppingEventList500>>(
 params?: GetShoppingEventListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getShoppingEventList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetShoppingEventListQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Get a shopping event by id
 * @summary Obter evento de compras por id
 */
export const getShoppingEventById = (
    shoppingEventId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetShoppingEventById200>(
      {url: `/api/shopping-event/${shoppingEventId}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetShoppingEventByIdQueryKey = (shoppingEventId: string,) => {
    return [
    `/api/shopping-event/${shoppingEventId}`
    ] as const;
    }

    
export const getGetShoppingEventByIdQueryOptions = <TData = Awaited<ReturnType<typeof getShoppingEventById>>, TError = ErrorType<GetShoppingEventById401 | GetShoppingEventById404 | GetShoppingEventById500>>(shoppingEventId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getShoppingEventById>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetShoppingEventByIdQueryKey(shoppingEventId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getShoppingEventById>>> = ({ signal }) => getShoppingEventById(shoppingEventId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(shoppingEventId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getShoppingEventById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetShoppingEventByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getShoppingEventById>>>
export type GetShoppingEventByIdQueryError = ErrorType<GetShoppingEventById401 | GetShoppingEventById404 | GetShoppingEventById500>


export function useGetShoppingEventById<TData = Awaited<ReturnType<typeof getShoppingEventById>>, TError = ErrorType<GetShoppingEventById401 | GetShoppingEventById404 | GetShoppingEventById500>>(
 shoppingEventId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getShoppingEventById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getShoppingEventById>>,
          TError,
          Awaited<ReturnType<typeof getShoppingEventById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetShoppingEventById<TData = Awaited<ReturnType<typeof getShoppingEventById>>, TError = ErrorType<GetShoppingEventById401 | GetShoppingEventById404 | GetShoppingEventById500>>(
 shoppingEventId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getShoppingEventById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getShoppingEventById>>,
          TError,
          Awaited<ReturnType<typeof getShoppingEventById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetShoppingEventById<TData = Awaited<ReturnType<typeof getShoppingEventById>>, TError = ErrorType<GetShoppingEventById401 | GetShoppingEventById404 | GetShoppingEventById500>>(
 shoppingEventId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getShoppingEventById>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Obter evento de compras por id
 */

export function useGetShoppingEventById<TData = Awaited<ReturnType<typeof getShoppingEventById>>, TError = ErrorType<GetShoppingEventById401 | GetShoppingEventById404 | GetShoppingEventById500>>(
 shoppingEventId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getShoppingEventById>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetShoppingEventByIdQueryOptions(shoppingEventId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




