/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Grocery Store API
 * API de gerenciamento de compras
 * OpenAPI spec version: 1.0.0
 */

import type {
  MutationFunction,
  UseMutationOptions,
  UseMutationResult,
} from '@tanstack/react-query';
import { useMutation } from '@tanstack/react-query';
import type {
  BodyType,
  ErrorType,
} from '../../config/clients/custom-http-client';
import { customInstance } from '../../config/clients/custom-http-client';
import type { AddUser401, AddUser422, AddUser500, AddUserBody } from './types';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Adiciona um usuario externo
 * @summary Clerk - Adiciona um usuario
 */
export const addUser = (
  addUserBody: BodyType<AddUserBody>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<unknown>(
    {
      url: `/api/webhook-auth/add-user`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: addUserBody,
      signal,
    },
    options,
  );
};

export const getAddUserMutationOptions = <
  TError = ErrorType<AddUser401 | AddUser422 | AddUser500>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof addUser>>,
    TError,
    { data: BodyType<AddUserBody> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof addUser>>,
  TError,
  { data: BodyType<AddUserBody> },
  TContext
> => {
  const mutationKey = ['addUser'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof addUser>>,
    { data: BodyType<AddUserBody> }
  > = (props) => {
    const { data } = props ?? {};

    return addUser(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AddUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof addUser>>
>;
export type AddUserMutationBody = BodyType<AddUserBody>;
export type AddUserMutationError = ErrorType<
  AddUser401 | AddUser422 | AddUser500
>;

/**
 * @summary Clerk - Adiciona um usuario
 */
export const useAddUser = <
  TError = ErrorType<AddUser401 | AddUser422 | AddUser500>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof addUser>>,
    TError,
    { data: BodyType<AddUserBody> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof addUser>>,
  TError,
  { data: BodyType<AddUserBody> },
  TContext
> => {
  return useMutation(getAddUserMutationOptions(options));
};
