/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as ProtectedAppLayoutRouteImport } from './routes/_protected/app/layout'
import { Route as ProtectedAppIndexRouteImport } from './routes/_protected/app/index'
import { Route as ProtectedAppShoppingEventIndexRouteImport } from './routes/_protected/app/shopping-event/index'
import { Route as ProtectedAppMarketIndexRouteImport } from './routes/_protected/app/market/index'
import { Route as ProtectedAppFamilyIndexRouteImport } from './routes/_protected/app/family/index'
import { Route as ProtectedAppShoppingEventStartShoppingEventRouteImport } from './routes/_protected/app/shopping-event/start-shopping-event'
import { Route as ProtectedAppShoppingEventShoppingEventIdRouteImport } from './routes/_protected/app/shopping-event/$shoppingEventId'
import { Route as ProtectedAppMarketNewMarketRouteImport } from './routes/_protected/app/market/new-market'
import { Route as ProtectedAppMarketUpdateMarketIdRouteImport } from './routes/_protected/app/market/update/$marketId'

const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/_public/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedAppLayoutRoute = ProtectedAppLayoutRouteImport.update({
  id: '/_protected/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedAppIndexRoute = ProtectedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedAppLayoutRoute,
} as any)
const ProtectedAppShoppingEventIndexRoute =
  ProtectedAppShoppingEventIndexRouteImport.update({
    id: '/shopping-event/',
    path: '/shopping-event/',
    getParentRoute: () => ProtectedAppLayoutRoute,
  } as any)
const ProtectedAppMarketIndexRoute = ProtectedAppMarketIndexRouteImport.update({
  id: '/market/',
  path: '/market/',
  getParentRoute: () => ProtectedAppLayoutRoute,
} as any)
const ProtectedAppFamilyIndexRoute = ProtectedAppFamilyIndexRouteImport.update({
  id: '/family/',
  path: '/family/',
  getParentRoute: () => ProtectedAppLayoutRoute,
} as any)
const ProtectedAppShoppingEventStartShoppingEventRoute =
  ProtectedAppShoppingEventStartShoppingEventRouteImport.update({
    id: '/shopping-event/start-shopping-event',
    path: '/shopping-event/start-shopping-event',
    getParentRoute: () => ProtectedAppLayoutRoute,
  } as any)
const ProtectedAppShoppingEventShoppingEventIdRoute =
  ProtectedAppShoppingEventShoppingEventIdRouteImport.update({
    id: '/shopping-event/$shoppingEventId',
    path: '/shopping-event/$shoppingEventId',
    getParentRoute: () => ProtectedAppLayoutRoute,
  } as any)
const ProtectedAppMarketNewMarketRoute =
  ProtectedAppMarketNewMarketRouteImport.update({
    id: '/market/new-market',
    path: '/market/new-market',
    getParentRoute: () => ProtectedAppLayoutRoute,
  } as any)
const ProtectedAppMarketUpdateMarketIdRoute =
  ProtectedAppMarketUpdateMarketIdRouteImport.update({
    id: '/market/update/$marketId',
    path: '/market/update/$marketId',
    getParentRoute: () => ProtectedAppLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/app': typeof ProtectedAppLayoutRouteWithChildren
  '/': typeof PublicIndexRoute
  '/app/': typeof ProtectedAppIndexRoute
  '/app/market/new-market': typeof ProtectedAppMarketNewMarketRoute
  '/app/shopping-event/$shoppingEventId': typeof ProtectedAppShoppingEventShoppingEventIdRoute
  '/app/shopping-event/start-shopping-event': typeof ProtectedAppShoppingEventStartShoppingEventRoute
  '/app/family/': typeof ProtectedAppFamilyIndexRoute
  '/app/market/': typeof ProtectedAppMarketIndexRoute
  '/app/shopping-event/': typeof ProtectedAppShoppingEventIndexRoute
  '/app/market/update/$marketId': typeof ProtectedAppMarketUpdateMarketIdRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/app': typeof ProtectedAppIndexRoute
  '/app/market/new-market': typeof ProtectedAppMarketNewMarketRoute
  '/app/shopping-event/$shoppingEventId': typeof ProtectedAppShoppingEventShoppingEventIdRoute
  '/app/shopping-event/start-shopping-event': typeof ProtectedAppShoppingEventStartShoppingEventRoute
  '/app/family': typeof ProtectedAppFamilyIndexRoute
  '/app/market': typeof ProtectedAppMarketIndexRoute
  '/app/shopping-event': typeof ProtectedAppShoppingEventIndexRoute
  '/app/market/update/$marketId': typeof ProtectedAppMarketUpdateMarketIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected/app': typeof ProtectedAppLayoutRouteWithChildren
  '/_public/': typeof PublicIndexRoute
  '/_protected/app/': typeof ProtectedAppIndexRoute
  '/_protected/app/market/new-market': typeof ProtectedAppMarketNewMarketRoute
  '/_protected/app/shopping-event/$shoppingEventId': typeof ProtectedAppShoppingEventShoppingEventIdRoute
  '/_protected/app/shopping-event/start-shopping-event': typeof ProtectedAppShoppingEventStartShoppingEventRoute
  '/_protected/app/family/': typeof ProtectedAppFamilyIndexRoute
  '/_protected/app/market/': typeof ProtectedAppMarketIndexRoute
  '/_protected/app/shopping-event/': typeof ProtectedAppShoppingEventIndexRoute
  '/_protected/app/market/update/$marketId': typeof ProtectedAppMarketUpdateMarketIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/app'
    | '/'
    | '/app/'
    | '/app/market/new-market'
    | '/app/shopping-event/$shoppingEventId'
    | '/app/shopping-event/start-shopping-event'
    | '/app/family/'
    | '/app/market/'
    | '/app/shopping-event/'
    | '/app/market/update/$marketId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/app/market/new-market'
    | '/app/shopping-event/$shoppingEventId'
    | '/app/shopping-event/start-shopping-event'
    | '/app/family'
    | '/app/market'
    | '/app/shopping-event'
    | '/app/market/update/$marketId'
  id:
    | '__root__'
    | '/_protected/app'
    | '/_public/'
    | '/_protected/app/'
    | '/_protected/app/market/new-market'
    | '/_protected/app/shopping-event/$shoppingEventId'
    | '/_protected/app/shopping-event/start-shopping-event'
    | '/_protected/app/family/'
    | '/_protected/app/market/'
    | '/_protected/app/shopping-event/'
    | '/_protected/app/market/update/$marketId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedAppLayoutRoute: typeof ProtectedAppLayoutRouteWithChildren
  PublicIndexRoute: typeof PublicIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/app': {
      id: '/_protected/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof ProtectedAppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/app/': {
      id: '/_protected/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof ProtectedAppIndexRouteImport
      parentRoute: typeof ProtectedAppLayoutRoute
    }
    '/_protected/app/shopping-event/': {
      id: '/_protected/app/shopping-event/'
      path: '/shopping-event'
      fullPath: '/app/shopping-event/'
      preLoaderRoute: typeof ProtectedAppShoppingEventIndexRouteImport
      parentRoute: typeof ProtectedAppLayoutRoute
    }
    '/_protected/app/market/': {
      id: '/_protected/app/market/'
      path: '/market'
      fullPath: '/app/market/'
      preLoaderRoute: typeof ProtectedAppMarketIndexRouteImport
      parentRoute: typeof ProtectedAppLayoutRoute
    }
    '/_protected/app/family/': {
      id: '/_protected/app/family/'
      path: '/family'
      fullPath: '/app/family/'
      preLoaderRoute: typeof ProtectedAppFamilyIndexRouteImport
      parentRoute: typeof ProtectedAppLayoutRoute
    }
    '/_protected/app/shopping-event/start-shopping-event': {
      id: '/_protected/app/shopping-event/start-shopping-event'
      path: '/shopping-event/start-shopping-event'
      fullPath: '/app/shopping-event/start-shopping-event'
      preLoaderRoute: typeof ProtectedAppShoppingEventStartShoppingEventRouteImport
      parentRoute: typeof ProtectedAppLayoutRoute
    }
    '/_protected/app/shopping-event/$shoppingEventId': {
      id: '/_protected/app/shopping-event/$shoppingEventId'
      path: '/shopping-event/$shoppingEventId'
      fullPath: '/app/shopping-event/$shoppingEventId'
      preLoaderRoute: typeof ProtectedAppShoppingEventShoppingEventIdRouteImport
      parentRoute: typeof ProtectedAppLayoutRoute
    }
    '/_protected/app/market/new-market': {
      id: '/_protected/app/market/new-market'
      path: '/market/new-market'
      fullPath: '/app/market/new-market'
      preLoaderRoute: typeof ProtectedAppMarketNewMarketRouteImport
      parentRoute: typeof ProtectedAppLayoutRoute
    }
    '/_protected/app/market/update/$marketId': {
      id: '/_protected/app/market/update/$marketId'
      path: '/market/update/$marketId'
      fullPath: '/app/market/update/$marketId'
      preLoaderRoute: typeof ProtectedAppMarketUpdateMarketIdRouteImport
      parentRoute: typeof ProtectedAppLayoutRoute
    }
  }
}

interface ProtectedAppLayoutRouteChildren {
  ProtectedAppIndexRoute: typeof ProtectedAppIndexRoute
  ProtectedAppMarketNewMarketRoute: typeof ProtectedAppMarketNewMarketRoute
  ProtectedAppShoppingEventShoppingEventIdRoute: typeof ProtectedAppShoppingEventShoppingEventIdRoute
  ProtectedAppShoppingEventStartShoppingEventRoute: typeof ProtectedAppShoppingEventStartShoppingEventRoute
  ProtectedAppFamilyIndexRoute: typeof ProtectedAppFamilyIndexRoute
  ProtectedAppMarketIndexRoute: typeof ProtectedAppMarketIndexRoute
  ProtectedAppShoppingEventIndexRoute: typeof ProtectedAppShoppingEventIndexRoute
  ProtectedAppMarketUpdateMarketIdRoute: typeof ProtectedAppMarketUpdateMarketIdRoute
}

const ProtectedAppLayoutRouteChildren: ProtectedAppLayoutRouteChildren = {
  ProtectedAppIndexRoute: ProtectedAppIndexRoute,
  ProtectedAppMarketNewMarketRoute: ProtectedAppMarketNewMarketRoute,
  ProtectedAppShoppingEventShoppingEventIdRoute:
    ProtectedAppShoppingEventShoppingEventIdRoute,
  ProtectedAppShoppingEventStartShoppingEventRoute:
    ProtectedAppShoppingEventStartShoppingEventRoute,
  ProtectedAppFamilyIndexRoute: ProtectedAppFamilyIndexRoute,
  ProtectedAppMarketIndexRoute: ProtectedAppMarketIndexRoute,
  ProtectedAppShoppingEventIndexRoute: ProtectedAppShoppingEventIndexRoute,
  ProtectedAppMarketUpdateMarketIdRoute: ProtectedAppMarketUpdateMarketIdRoute,
}

const ProtectedAppLayoutRouteWithChildren =
  ProtectedAppLayoutRoute._addFileChildren(ProtectedAppLayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ProtectedAppLayoutRoute: ProtectedAppLayoutRouteWithChildren,
  PublicIndexRoute: PublicIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
