/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicSigninRouteImport } from './routes/_public/signin'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ProtectedShoppingEventIndexRouteImport } from './routes/_protected/shopping-event/index'
import { Route as ProtectedMarketIndexRouteImport } from './routes/_protected/market/index'
import { Route as ProtectedFamilyIndexRouteImport } from './routes/_protected/family/index'
import { Route as ProtectedShoppingEventStartShoppingEventRouteImport } from './routes/_protected/shopping-event/start-shopping-event'
import { Route as ProtectedShoppingEventShoppingEventIdRouteImport } from './routes/_protected/shopping-event/$shoppingEventId'
import { Route as ProtectedMarketNewMarketRouteImport } from './routes/_protected/market/new-market'
import { Route as ProtectedMarketUpdateMarketIdRouteImport } from './routes/_protected/market/update/$marketId'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/_public/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicSigninRoute = PublicSigninRouteImport.update({
  id: '/_public/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedShoppingEventIndexRoute =
  ProtectedShoppingEventIndexRouteImport.update({
    id: '/shopping-event/',
    path: '/shopping-event/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedMarketIndexRoute = ProtectedMarketIndexRouteImport.update({
  id: '/market/',
  path: '/market/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedFamilyIndexRoute = ProtectedFamilyIndexRouteImport.update({
  id: '/family/',
  path: '/family/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedShoppingEventStartShoppingEventRoute =
  ProtectedShoppingEventStartShoppingEventRouteImport.update({
    id: '/shopping-event/start-shopping-event',
    path: '/shopping-event/start-shopping-event',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedShoppingEventShoppingEventIdRoute =
  ProtectedShoppingEventShoppingEventIdRouteImport.update({
    id: '/shopping-event/$shoppingEventId',
    path: '/shopping-event/$shoppingEventId',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedMarketNewMarketRoute =
  ProtectedMarketNewMarketRouteImport.update({
    id: '/market/new-market',
    path: '/market/new-market',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedMarketUpdateMarketIdRoute =
  ProtectedMarketUpdateMarketIdRouteImport.update({
    id: '/market/update/$marketId',
    path: '/market/update/$marketId',
    getParentRoute: () => ProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/signin': typeof PublicSigninRoute
  '/market/new-market': typeof ProtectedMarketNewMarketRoute
  '/shopping-event/$shoppingEventId': typeof ProtectedShoppingEventShoppingEventIdRoute
  '/shopping-event/start-shopping-event': typeof ProtectedShoppingEventStartShoppingEventRoute
  '/family/': typeof ProtectedFamilyIndexRoute
  '/market/': typeof ProtectedMarketIndexRoute
  '/shopping-event/': typeof ProtectedShoppingEventIndexRoute
  '/market/update/$marketId': typeof ProtectedMarketUpdateMarketIdRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/signin': typeof PublicSigninRoute
  '/market/new-market': typeof ProtectedMarketNewMarketRoute
  '/shopping-event/$shoppingEventId': typeof ProtectedShoppingEventShoppingEventIdRoute
  '/shopping-event/start-shopping-event': typeof ProtectedShoppingEventStartShoppingEventRoute
  '/family': typeof ProtectedFamilyIndexRoute
  '/market': typeof ProtectedMarketIndexRoute
  '/shopping-event': typeof ProtectedShoppingEventIndexRoute
  '/market/update/$marketId': typeof ProtectedMarketUpdateMarketIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_public/signin': typeof PublicSigninRoute
  '/_public/': typeof PublicIndexRoute
  '/_protected/market/new-market': typeof ProtectedMarketNewMarketRoute
  '/_protected/shopping-event/$shoppingEventId': typeof ProtectedShoppingEventShoppingEventIdRoute
  '/_protected/shopping-event/start-shopping-event': typeof ProtectedShoppingEventStartShoppingEventRoute
  '/_protected/family/': typeof ProtectedFamilyIndexRoute
  '/_protected/market/': typeof ProtectedMarketIndexRoute
  '/_protected/shopping-event/': typeof ProtectedShoppingEventIndexRoute
  '/_protected/market/update/$marketId': typeof ProtectedMarketUpdateMarketIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/signin'
    | '/market/new-market'
    | '/shopping-event/$shoppingEventId'
    | '/shopping-event/start-shopping-event'
    | '/family/'
    | '/market/'
    | '/shopping-event/'
    | '/market/update/$marketId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/signin'
    | '/market/new-market'
    | '/shopping-event/$shoppingEventId'
    | '/shopping-event/start-shopping-event'
    | '/family'
    | '/market'
    | '/shopping-event'
    | '/market/update/$marketId'
  id:
    | '__root__'
    | '/_protected'
    | '/_protected/dashboard'
    | '/_public/signin'
    | '/_public/'
    | '/_protected/market/new-market'
    | '/_protected/shopping-event/$shoppingEventId'
    | '/_protected/shopping-event/start-shopping-event'
    | '/_protected/family/'
    | '/_protected/market/'
    | '/_protected/shopping-event/'
    | '/_protected/market/update/$marketId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  PublicSigninRoute: typeof PublicSigninRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/signin': {
      id: '/_public/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof PublicSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/shopping-event/': {
      id: '/_protected/shopping-event/'
      path: '/shopping-event'
      fullPath: '/shopping-event/'
      preLoaderRoute: typeof ProtectedShoppingEventIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/market/': {
      id: '/_protected/market/'
      path: '/market'
      fullPath: '/market/'
      preLoaderRoute: typeof ProtectedMarketIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/family/': {
      id: '/_protected/family/'
      path: '/family'
      fullPath: '/family/'
      preLoaderRoute: typeof ProtectedFamilyIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/shopping-event/start-shopping-event': {
      id: '/_protected/shopping-event/start-shopping-event'
      path: '/shopping-event/start-shopping-event'
      fullPath: '/shopping-event/start-shopping-event'
      preLoaderRoute: typeof ProtectedShoppingEventStartShoppingEventRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/shopping-event/$shoppingEventId': {
      id: '/_protected/shopping-event/$shoppingEventId'
      path: '/shopping-event/$shoppingEventId'
      fullPath: '/shopping-event/$shoppingEventId'
      preLoaderRoute: typeof ProtectedShoppingEventShoppingEventIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/market/new-market': {
      id: '/_protected/market/new-market'
      path: '/market/new-market'
      fullPath: '/market/new-market'
      preLoaderRoute: typeof ProtectedMarketNewMarketRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/market/update/$marketId': {
      id: '/_protected/market/update/$marketId'
      path: '/market/update/$marketId'
      fullPath: '/market/update/$marketId'
      preLoaderRoute: typeof ProtectedMarketUpdateMarketIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedMarketNewMarketRoute: typeof ProtectedMarketNewMarketRoute
  ProtectedShoppingEventShoppingEventIdRoute: typeof ProtectedShoppingEventShoppingEventIdRoute
  ProtectedShoppingEventStartShoppingEventRoute: typeof ProtectedShoppingEventStartShoppingEventRoute
  ProtectedFamilyIndexRoute: typeof ProtectedFamilyIndexRoute
  ProtectedMarketIndexRoute: typeof ProtectedMarketIndexRoute
  ProtectedShoppingEventIndexRoute: typeof ProtectedShoppingEventIndexRoute
  ProtectedMarketUpdateMarketIdRoute: typeof ProtectedMarketUpdateMarketIdRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedMarketNewMarketRoute: ProtectedMarketNewMarketRoute,
  ProtectedShoppingEventShoppingEventIdRoute:
    ProtectedShoppingEventShoppingEventIdRoute,
  ProtectedShoppingEventStartShoppingEventRoute:
    ProtectedShoppingEventStartShoppingEventRoute,
  ProtectedFamilyIndexRoute: ProtectedFamilyIndexRoute,
  ProtectedMarketIndexRoute: ProtectedMarketIndexRoute,
  ProtectedShoppingEventIndexRoute: ProtectedShoppingEventIndexRoute,
  ProtectedMarketUpdateMarketIdRoute: ProtectedMarketUpdateMarketIdRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  PublicSigninRoute: PublicSigninRoute,
  PublicIndexRoute: PublicIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
